/**
 * Grammar Rule Constants — Comprehensive English Grammar Reference
 * 75 Days Hard English Platform
 * 500+ lines covering all major grammar topics
 */

// ── 1. ALL 12 TENSES ──────────────────────────────────────────────────────────
export const TENSES = {
  SIMPLE_PRESENT: {
    id: 'simple-present',
    label: 'Simple Present',
    hindiLabel: 'सामान्य वर्तमान काल',
    structure: 'S + V(s/es) + O',
    negative: 'S + do/does + not + V1 + O',
    question: 'Do/Does + S + V1 + O?',
    use: 'Habits, routines, universal truths, general facts',
    hindiUse: 'आदत, दिनचर्या, सामान्य सच्चाई',
    example: 'She plays cricket every day.',
    negativeExample: 'She does not play cricket on Sundays.',
    questionExample: 'Does she play cricket?',
    hindiExample: 'वह रोज़ क्रिकेट खेलती है।',
    keyWords: ['always', 'usually', 'often', 'sometimes', 'never', 'every day', 'daily'],
    commonMistakes: [
      { wrong: 'She play cricket.', correct: 'She plays cricket.', why: 'He/She/It के साथ verb में s/es लगता है' },
      { wrong: 'He don\'t know.', correct: 'He doesn\'t know.', why: 'Third person singular के साथ doesn\'t' },
    ],
  },
  PRESENT_CONTINUOUS: {
    id: 'present-continuous',
    label: 'Present Continuous',
    hindiLabel: 'अपूर्ण वर्तमान काल',
    structure: 'S + is/am/are + V-ing + O',
    negative: 'S + is/am/are + not + V-ing + O',
    question: 'Is/Am/Are + S + V-ing + O?',
    use: 'Actions happening right now, temporary situations, future arrangements',
    hindiUse: 'अभी हो रही क्रिया, अस्थायी स्थिति',
    example: 'She is playing cricket right now.',
    negativeExample: 'She is not playing cricket today.',
    questionExample: 'Is she playing cricket?',
    hindiExample: 'वह अभी क्रिकेट खेल रही है।',
    keyWords: ['now', 'right now', 'at the moment', 'currently', 'today', 'this week'],
    commonMistakes: [
      { wrong: 'She is play cricket.', correct: 'She is playing cricket.', why: 'Continuous में -ing form लगती है' },
      { wrong: 'I am knowing him.', correct: 'I know him.', why: 'Stative verbs (know, love, want) -ing नहीं लेते' },
    ],
  },
  PRESENT_PERFECT: {
    id: 'present-perfect',
    label: 'Present Perfect',
    hindiLabel: 'पूर्ण वर्तमान काल',
    structure: 'S + has/have + V3 + O',
    negative: 'S + has/have + not + V3 + O',
    question: 'Has/Have + S + V3 + O?',
    use: 'Past actions with present relevance, life experiences, recent actions',
    hindiUse: 'जो अभी-अभी हुआ, या जिसका असर अभी है',
    example: 'She has played cricket for India.',
    negativeExample: 'She has not played today.',
    questionExample: 'Have you eaten lunch?',
    hindiExample: 'वह भारत के लिए क्रिकेट खेल चुकी है।',
    keyWords: ['already', 'yet', 'just', 'ever', 'never', 'so far', 'recently', 'since', 'for'],
    commonMistakes: [
      { wrong: 'I have went there.', correct: 'I have gone there.', why: 'V3 (gone) चाहिए, V2 (went) नहीं' },
      { wrong: 'She has came.', correct: 'She has come.', why: 'Come का V3 भी come है' },
    ],
  },
  PRESENT_PERF_CONT: {
    id: 'present-perf-cont',
    label: 'Present Perfect Continuous',
    hindiLabel: 'पूर्ण-अपूर्ण वर्तमान काल',
    structure: 'S + has/have + been + V-ing + O',
    negative: 'S + has/have + not + been + V-ing + O',
    question: 'Has/Have + S + been + V-ing + O?',
    use: 'Action started in past, still continuing in present',
    hindiUse: 'जो काम पहले शुरू हुआ और अभी भी चल रहा है',
    example: 'She has been playing cricket since childhood.',
    negativeExample: 'I have not been feeling well lately.',
    questionExample: 'How long have you been waiting?',
    hindiExample: 'वह बचपन से क्रिकेट खेलती आ रही है।',
    keyWords: ['since', 'for', 'how long', 'all day', 'lately'],
    commonMistakes: [
      { wrong: 'She has been play for 2 hours.', correct: 'She has been playing for 2 hours.', why: 'been के बाद V-ing form' },
    ],
  },
  SIMPLE_PAST: {
    id: 'simple-past',
    label: 'Simple Past',
    hindiLabel: 'सामान्य भूतकाल',
    structure: 'S + V2 + O',
    negative: 'S + did + not + V1 + O',
    question: 'Did + S + V1 + O?',
    use: 'Completed actions in the past, historical events, past habits',
    hindiUse: 'बीती हुई घटनाएं, पूरे हो चुके काम',
    example: 'She played cricket yesterday.',
    negativeExample: 'She did not play yesterday.',
    questionExample: 'Did she play cricket?',
    hindiExample: 'उसने कल क्रिकेट खेली।',
    keyWords: ['yesterday', 'ago', 'last week/year/month', 'in 2010', 'when I was young'],
    commonMistakes: [
      { wrong: 'She did not played.', correct: 'She did not play.', why: 'did के बाद V1 (base form) आती है' },
      { wrong: 'I goed to school.', correct: 'I went to school.', why: 'go का V2 irregular है: went' },
    ],
  },
  PAST_CONTINUOUS: {
    id: 'past-continuous',
    label: 'Past Continuous',
    hindiLabel: 'अपूर्ण भूतकाल',
    structure: 'S + was/were + V-ing + O',
    negative: 'S + was/were + not + V-ing + O',
    question: 'Was/Were + S + V-ing + O?',
    use: 'Action in progress at a specific time in the past',
    hindiUse: 'भूतकाल में किसी वक्त जारी था',
    example: 'She was playing cricket at 5 PM yesterday.',
    negativeExample: 'They were not watching TV.',
    questionExample: 'Was she sleeping when you called?',
    hindiExample: 'वह कल शाम 5 बजे क्रिकेट खेल रही थी।',
    keyWords: ['while', 'when', 'at that time', 'at 5 PM', 'all morning'],
    commonMistakes: [
      { wrong: 'They was playing.', correct: 'They were playing.', why: 'Plural subject के साथ were' },
    ],
  },
  PAST_PERFECT: {
    id: 'past-perfect',
    label: 'Past Perfect',
    hindiLabel: 'पूर्ण भूतकाल',
    structure: 'S + had + V3 + O',
    negative: 'S + had + not + V3 + O',
    question: 'Had + S + V3 + O?',
    use: 'Action completed before another past action',
    hindiUse: 'दो भूतकाल की घटनाओं में से जो पहले हुई',
    example: 'She had played cricket before it rained.',
    negativeExample: 'He had not eaten before the meeting.',
    questionExample: 'Had you met her before the party?',
    hindiExample: 'बारिश आने से पहले वह क्रिकेट खेल चुकी थी।',
    keyWords: ['before', 'after', 'by the time', 'already', 'when', 'as soon as'],
    commonMistakes: [
      { wrong: 'She had went.', correct: 'She had gone.', why: 'had के बाद V3 आती है' },
    ],
  },
  PAST_PERF_CONT: {
    id: 'past-perf-cont',
    label: 'Past Perfect Continuous',
    hindiLabel: 'पूर्ण-अपूर्ण भूतकाल',
    structure: 'S + had + been + V-ing + O',
    negative: 'S + had + not + been + V-ing + O',
    question: 'Had + S + been + V-ing + O?',
    use: 'Action that was ongoing up to a certain point in the past',
    hindiUse: 'भूतकाल में किसी बिंदु तक जारी रहने वाला काम',
    example: 'She had been playing cricket for 2 hours before it rained.',
    negativeExample: 'He had not been feeling well for days.',
    questionExample: 'Had they been waiting long?',
    hindiExample: 'बारिश से पहले वह 2 घंटे से खेल रही थी।',
    keyWords: ['for', 'since', 'before', 'when', 'by the time'],
    commonMistakes: [
      { wrong: 'She had been play.', correct: 'She had been playing.', why: 'been के बाद -ing' },
    ],
  },
  SIMPLE_FUTURE: {
    id: 'simple-future',
    label: 'Simple Future',
    hindiLabel: 'सामान्य भविष्य काल',
    structure: 'S + will + V1 + O',
    negative: 'S + will + not + V1 + O',
    question: 'Will + S + V1 + O?',
    use: 'Decisions made at moment of speaking, predictions, promises',
    hindiUse: 'आगे होने वाली घटना, निर्णय, वादा',
    example: 'She will play cricket tomorrow.',
    negativeExample: 'She will not play tomorrow.',
    questionExample: 'Will she play cricket?',
    hindiExample: 'वह कल क्रिकेट खेलेगी।',
    keyWords: ['tomorrow', 'next week/year', 'soon', 'in the future', 'someday'],
    commonMistakes: [
      { wrong: 'She will plays cricket.', correct: 'She will play cricket.', why: 'will के बाद V1 (base form)' },
      { wrong: 'I will to go.', correct: 'I will go.', why: 'will के बाद to नहीं' },
    ],
  },
  FUTURE_CONTINUOUS: {
    id: 'future-continuous',
    label: 'Future Continuous',
    hindiLabel: 'अपूर्ण भविष्य काल',
    structure: 'S + will + be + V-ing + O',
    negative: 'S + will + not + be + V-ing + O',
    question: 'Will + S + be + V-ing + O?',
    use: 'Action in progress at a specific future time',
    hindiUse: 'भविष्य में किसी समय जारी रहने वाला काम',
    example: 'She will be playing cricket at 5 PM tomorrow.',
    negativeExample: 'I will not be working on Sunday.',
    questionExample: 'Will you be sleeping at midnight?',
    hindiExample: 'वह कल शाम 5 बजे क्रिकेट खेल रही होगी।',
    keyWords: ['at this time tomorrow', 'at 5 PM tomorrow', 'this time next week'],
    commonMistakes: [
      { wrong: 'She will be play.', correct: 'She will be playing.', why: 'will be के बाद -ing' },
    ],
  },
  FUTURE_PERFECT: {
    id: 'future-perfect',
    label: 'Future Perfect',
    hindiLabel: 'पूर्ण भविष्य काल',
    structure: 'S + will + have + V3 + O',
    negative: 'S + will + not + have + V3 + O',
    question: 'Will + S + have + V3 + O?',
    use: 'Action that will be completed before a future point',
    hindiUse: 'भविष्य में किसी समय तक पूरा हो जाने वाला काम',
    example: 'She will have played 100 matches by 2026.',
    negativeExample: 'I will not have finished by then.',
    questionExample: 'Will you have submitted the report by Friday?',
    hindiExample: '2026 तक वह 100 मैच खेल चुकी होगी।',
    keyWords: ['by then', 'by the time', 'by Monday', 'before', 'already'],
    commonMistakes: [
      { wrong: 'She will have went.', correct: 'She will have gone.', why: 'will have के बाद V3' },
    ],
  },
  FUTURE_PERF_CONT: {
    id: 'future-perf-cont',
    label: 'Future Perfect Continuous',
    hindiLabel: 'पूर्ण-अपूर्ण भविष्य काल',
    structure: 'S + will + have + been + V-ing + O',
    negative: 'S + will + not + have + been + V-ing + O',
    question: 'Will + S + have + been + V-ing + O?',
    use: 'Action that will have been ongoing for a duration up to a future time',
    hindiUse: 'भविष्य में किसी बिंदु तक एक निश्चित समय से जारी रहने वाला काम',
    example: 'By 2025, she will have been playing cricket for 10 years.',
    negativeExample: 'By next month, I will not have been working here for a year.',
    questionExample: 'By next year, will you have been studying for 2 years?',
    hindiExample: '2025 तक वह 10 साल से क्रिकेट खेलती आ रही होगी।',
    keyWords: ['by', 'for', 'since', 'by the time'],
    commonMistakes: [
      { wrong: 'She will have been play.', correct: 'She will have been playing.', why: 'have been के बाद -ing' },
    ],
  },
};

// ── 2. PARTS OF SPEECH ────────────────────────────────────────────────────────
export const PARTS_OF_SPEECH = [
  {
    id: 'noun',
    label: 'Noun',
    hindiLabel: 'संज्ञा',
    definition: 'A person, place, thing, or idea.',
    hindiDefinition: 'व्यक्ति, स्थान, वस्तु, या विचार का नाम',
    types: ['Proper Noun (Ram, Delhi)', 'Common Noun (boy, city)', 'Abstract Noun (love, truth)', 'Collective Noun (team, flock)', 'Material Noun (gold, water)'],
    example: 'dog, city, happiness, India, team',
    tip: 'जो नाम है — वो Noun है। राम, दिल्ली, खुशी, टीम',
  },
  {
    id: 'pronoun',
    label: 'Pronoun',
    hindiLabel: 'सर्वनाम',
    definition: 'Replaces a noun to avoid repetition.',
    hindiDefinition: 'Noun की जगह use होने वाला शब्द',
    types: ['Personal (I, he, she, they)', 'Possessive (my, his, her)', 'Reflexive (myself, himself)', 'Demonstrative (this, that)', 'Interrogative (who, which)', 'Relative (who, which, that)', 'Indefinite (someone, anyone)'],
    example: 'he, she, they, it, I, we, you',
    tip: 'Noun की जगह आता है — Ram → He, Sita → She',
  },
  {
    id: 'verb',
    label: 'Verb',
    hindiLabel: 'क्रिया',
    definition: 'An action, occurrence, or state of being.',
    hindiDefinition: 'काम, घटना, या अवस्था दर्शाने वाला शब्द',
    types: ['Action Verb (run, eat, write)', 'Stative Verb (know, love, seem)', 'Auxiliary Verb (is, have, do, will)', 'Modal Verb (can, must, should)', 'Transitive (needs object)', 'Intransitive (no object needed)'],
    example: 'run, is, think, eat, have, can',
    tip: 'जो काम होता है — वो Verb है। खाना, दौड़ना, है, था',
  },
  {
    id: 'adjective',
    label: 'Adjective',
    hindiLabel: 'विशेषण',
    definition: 'Describes or modifies a noun or pronoun.',
    hindiDefinition: 'Noun की विशेषता बताने वाला शब्द',
    types: ['Descriptive (tall, red)', 'Quantitative (some, many)', 'Demonstrative (this, those)', 'Possessive (my, their)', 'Interrogative (which, what)', 'Comparative (taller)', 'Superlative (tallest)'],
    example: 'tall, red, happy, some, this, my',
    tip: 'Noun से पहले — सुंदर लड़की → beautiful girl',
  },
  {
    id: 'adverb',
    label: 'Adverb',
    hindiLabel: 'क्रिया-विशेषण',
    definition: 'Modifies a verb, adjective, or another adverb.',
    hindiDefinition: 'Verb या Adjective की विशेषता बताने वाला शब्द',
    types: ['Manner (quickly, well)', 'Time (now, yesterday)', 'Place (here, there)', 'Frequency (always, never)', 'Degree (very, quite, too)'],
    example: 'quickly, very, well, here, always',
    tip: 'How? When? Where? — इन सवालों का जवाब Adverb है',
  },
  {
    id: 'preposition',
    label: 'Preposition',
    hindiLabel: 'सम्बन्धबोधक अव्यय',
    definition: 'Shows relationship between a noun and other words.',
    hindiDefinition: 'शब्दों के बीच संबंध दर्शाने वाला शब्द',
    types: ['Time (at, in, on)', 'Place (at, in, on, under)', 'Direction (to, from, into)', 'Manner (by, with)', 'Cause (because of, due to)'],
    example: 'in, on, at, with, by, from, to, under',
    tip: 'Noun के पहले आता है — in the room, on the table, at school',
  },
  {
    id: 'conjunction',
    label: 'Conjunction',
    hindiLabel: 'समुच्चयबोधक अव्यय',
    definition: 'Connects words, phrases, or clauses.',
    hindiDefinition: 'शब्दों या वाक्यों को जोड़ने वाला शब्द',
    types: ['Coordinating (and, but, or, so, yet, for, nor)', 'Subordinating (because, although, when, if, since)', 'Correlative (either-or, neither-nor, both-and)'],
    example: 'and, but, or, because, although, when, if',
    tip: 'जो जोड़े — वो Conjunction है। और, लेकिन, क्योंकि',
  },
  {
    id: 'interjection',
    label: 'Interjection',
    hindiLabel: 'विस्मयादिबोधक',
    definition: 'Expresses sudden emotion or exclamation.',
    hindiDefinition: 'अचानक भाव व्यक्त करने वाला शब्द',
    types: ['Joy (Hurray!, Yay!)', 'Surprise (Wow!, Oh!)', 'Pain (Ouch!, Ow!)', 'Displeasure (Ugh!, Yuck!)'],
    example: 'Oh!, Wow!, Ouch!, Hurray!, Alas!',
    tip: 'Feeling express करता है — Wow!, Oh no!, Hurray!',
  },
  {
    id: 'article',
    label: 'Article',
    hindiLabel: 'उपसर्ग (आर्टिकल)',
    definition: 'Defines a noun as specific (the) or general (a/an).',
    hindiDefinition: 'Noun को specific या general बनाने वाला शब्द',
    types: ['Definite Article: the', 'Indefinite Articles: a, an'],
    example: 'a book, an apple, the sun',
    tip: 'a = कोई एक, an = कोई एक (vowel sound), the = वह specific वाला',
  },
];

// ── 3. MODAL VERBS ────────────────────────────────────────────────────────────
export const MODAL_VERBS = {
  CAN: {
    modal: 'can',
    hindiMeaning: 'सकना (ability/permission)',
    uses: ['Ability: I can swim.', 'Permission: Can I go?', 'Possibility: It can happen.', 'Request: Can you help me?'],
    example: 'I can speak three languages.',
    negative: 'cannot / can\'t',
    pastForm: 'could',
    structure: 'S + can + V1',
    commonMistakes: [{ wrong: 'I can to swim.', correct: 'I can swim.', why: 'Modal के बाद to नहीं' }],
  },
  COULD: {
    modal: 'could',
    hindiMeaning: 'सकता था / सकते हैं (polite)',
    uses: ['Past ability: I could run fast.', 'Polite request: Could you help?', 'Possibility: It could rain.', 'Suggestion: You could try this.'],
    example: 'Could you please open the window?',
    negative: 'could not / couldn\'t',
    structure: 'S + could + V1',
    commonMistakes: [{ wrong: 'He could to swim.', correct: 'He could swim.', why: 'Modal के बाद to नहीं' }],
  },
  WILL: {
    modal: 'will',
    hindiMeaning: 'गा/गी/गे (future/certainty)',
    uses: ['Future: She will come.', 'Promise: I will help you.', 'Offer: I\'ll get it.', 'Prediction: It will rain.'],
    example: 'I will call you tomorrow.',
    negative: 'will not / won\'t',
    structure: 'S + will + V1',
    commonMistakes: [{ wrong: 'She will comes.', correct: 'She will come.', why: 'will के बाद V1 base form' }],
  },
  WOULD: {
    modal: 'would',
    hindiMeaning: 'गा/गी — conditional या polite',
    uses: ['Polite request: Would you help?', 'Conditional: I would go if I could.', 'Preference: I would prefer tea.', 'Past habit: We would go every year.'],
    example: 'I would like a cup of tea, please.',
    negative: 'would not / wouldn\'t',
    structure: 'S + would + V1',
    commonMistakes: [{ wrong: 'I would to go.', correct: 'I would go.', why: 'would के बाद to नहीं' }],
  },
  SHALL: {
    modal: 'shall',
    hindiMeaning: 'होगा — formal future / suggestion',
    uses: ['Formal future (I/we): I shall return.', 'Suggestion: Shall we begin?', 'Offer: Shall I help you?', 'Legal: The tenant shall pay rent.'],
    example: 'Shall we start the meeting?',
    negative: 'shall not / shan\'t',
    structure: 'S + shall + V1',
    tip: 'Shall mainly I और We के साथ — formal context में',
  },
  SHOULD: {
    modal: 'should',
    hindiMeaning: 'चाहिए (advice/obligation)',
    uses: ['Advice: You should rest.', 'Recommendation: You should try this.', 'Expectation: He should be here.', 'Regret: I should have studied.'],
    example: 'You should drink more water.',
    negative: 'should not / shouldn\'t',
    structure: 'S + should + V1',
    commonMistakes: [{ wrong: 'You should to rest.', correct: 'You should rest.', why: 'should के बाद to नहीं' }],
  },
  MAY: {
    modal: 'may',
    hindiMeaning: 'हो सकता है / सकते हैं (possibility/permission)',
    uses: ['Possibility: It may rain.', 'Formal permission: May I come in?', 'Wish: May you succeed!', 'Concession: He may be right.'],
    example: 'You may leave early today.',
    negative: 'may not',
    structure: 'S + may + V1',
    tip: 'May = formal permission; Can = informal permission',
  },
  MIGHT: {
    modal: 'might',
    hindiMeaning: 'शायद हो सकता है (weak possibility)',
    uses: ['Weak possibility: She might come.', 'Past possibility: He might have left.', 'Suggestion: You might want to try.'],
    example: 'It might snow tomorrow.',
    negative: 'might not',
    structure: 'S + might + V1',
    tip: 'May = 50% chance; Might = less than 50% chance',
  },
  MUST: {
    modal: 'must',
    hindiMeaning: 'ज़रूर करना चाहिए / होना चाहिए',
    uses: ['Strong obligation: You must wear seatbelt.', 'Prohibition: You must not smoke.', 'Logical deduction: He must be tired.', 'Recommendation: You must visit Taj Mahal.'],
    example: 'You must submit the form by Friday.',
    negative: 'must not / mustn\'t',
    structure: 'S + must + V1',
    commonMistakes: [{ wrong: 'You must to go.', correct: 'You must go.', why: 'must के बाद to नहीं' }],
  },
  OUGHT_TO: {
    modal: 'ought to',
    hindiMeaning: 'करना उचित है (moral obligation)',
    uses: ['Moral duty: You ought to apologize.', 'Expectation: He ought to be here.', 'Advice: You ought to see a doctor.'],
    example: 'You ought to respect your elders.',
    negative: 'ought not to',
    structure: 'S + ought to + V1',
    tip: 'Should और ought to similar हैं — ought to थोड़ा stronger',
  },
  NEED: {
    modal: 'need',
    hindiMeaning: 'ज़रूरत है',
    uses: ['Necessity: You need to work hard.', 'Modal (negative): You need not worry.', 'Question: Need I say more?'],
    example: 'You need not come tomorrow.',
    negative: 'need not / needn\'t',
    structure: 'S + need + V1 (modal) / S + need + to + V1 (main verb)',
    tip: 'Need not = Modal; Don\'t need to = Main verb negative',
  },
  USED_TO: {
    modal: 'used to',
    hindiMeaning: 'पहले करता था (past habit)',
    uses: ['Past habit: I used to wake up at 5.', 'Past state: There used to be a temple here.'],
    example: 'I used to play cricket when I was young.',
    negative: 'used not to / didn\'t use to',
    structure: 'S + used to + V1',
    tip: 'Used to = पहले करता था, अब नहीं; Be used to = अभ्यस्त होना',
  },
  DARE: {
    modal: 'dare',
    hindiMeaning: 'हिम्मत करना',
    uses: ['Challenge: How dare you!', 'Doubt: I dare not say it.', 'Question: Dare she go alone?'],
    example: 'How dare you speak to me like that!',
    negative: 'dare not / daren\'t',
    structure: 'S + dare + V1',
  },
};

// ── 4. ARTICLES ───────────────────────────────────────────────────────────────
export const ARTICLE_RULES = {
  A: {
    article: 'a',
    use: 'Before singular countable nouns starting with consonant sound',
    hindiUse: 'व्यंजन ध्वनि से शुरू होने वाले singular nouns के पहले',
    examples: ['a book', 'a car', 'a university (sounds like "you")', 'a European (sounds like "you")'],
    rules: [
      'Use before consonant sounds: a cat, a dog, a man',
      'Use before "u" sounding like "you": a university, a uniform',
      'Use before "eu" and "ew" sounds: a European, a ewe',
      'Use for first mention: I saw a dog. The dog was big.',
    ],
    commonMistakes: [
      { wrong: 'a apple', correct: 'an apple', why: 'apple vowel sound (a) से शुरू' },
      { wrong: 'a umbrella', correct: 'an umbrella', why: 'umbrella vowel sound से शुरू' },
    ],
  },
  AN: {
    article: 'an',
    use: 'Before singular countable nouns starting with a vowel sound',
    hindiUse: 'स्वर ध्वनि (a, e, i, o, u sound) से शुरू होने वाले nouns के पहले',
    examples: ['an apple', 'an orange', 'an hour (h silent)', 'an honest person', 'an MBA'],
    rules: [
      'Use before vowel sounds: an apple, an egg, an island',
      'Use when "h" is silent: an hour, an honest man, an heir',
      'Use before abbreviations starting with vowel sound: an MBA, an NGO, an SSC exam',
      'Sound matters, not spelling: an umbrella, an X-ray, an MP',
    ],
    commonMistakes: [
      { wrong: 'a honest man', correct: 'an honest man', why: 'honest में h silent है, vowel sound से शुरू' },
      { wrong: 'an university', correct: 'a university', why: 'university "you" sound से शुरू — consonant sound' },
    ],
  },
  THE: {
    article: 'the',
    use: 'Before specific, unique, or previously mentioned nouns',
    hindiUse: 'Specific, unique, या पहले mention की गई चीज़ से पहले',
    examples: ['the sun', 'the moon', 'the book I read', 'the President of India'],
    rules: [
      'Unique things: the sun, the moon, the earth, the sky',
      'Already mentioned: I saw a dog. The dog barked.',
      'Superlatives: the best, the tallest, the most beautiful',
      'Ordinals: the first, the second, the last',
      'Mountain ranges: the Himalayas, the Alps',
      'Rivers/seas/oceans: the Ganga, the Pacific, the Atlantic',
      'Countries with plural/united/republic: the USA, the UAE, the UK',
      'Newspapers: the Times of India, the Hindu',
      'Musical instruments: play the guitar, the piano',
    ],
    commonMistakes: [
      { wrong: 'I like the cricket.', correct: 'I like cricket.', why: 'Sports/games से पहले article नहीं' },
      { wrong: 'She is a best student.', correct: 'She is the best student.', why: 'Superlative से पहले the' },
    ],
  },
  NO_ARTICLE: {
    article: '(no article / zero article)',
    use: 'Before plural nouns in general sense, uncountable nouns, languages, sports, meals',
    hindiUse: 'General plural nouns, uncountable nouns, sports, meals, languages के पहले',
    examples: ['Dogs are loyal.', 'I like music.', 'She speaks Hindi.', 'He plays cricket.', 'Have breakfast.'],
    rules: [
      'General plural nouns: Dogs are friendly.',
      'Uncountable nouns in general: I love music. Water is essential.',
      'Languages: She speaks French.',
      'Sports and games: I play cricket.',
      'Meals: Have lunch. Eat breakfast.',
      'Academic subjects: I study maths.',
      'Most proper nouns: India, Ram, Delhi',
      'Possessives: my book, his car (not the my book)',
    ],
    commonMistakes: [
      { wrong: 'the India', correct: 'India', why: 'Country names (single) से पहले the नहीं' },
      { wrong: 'the breakfast', correct: 'breakfast', why: 'Meals से पहले generally article नहीं' },
    ],
  },
};

// ── 5. PRONOUNS ────────────────────────────────────────────────────────────────
export const PRONOUNS = {
  PERSONAL: {
    type: 'Personal Pronouns',
    hindiLabel: 'व्यक्तिवाचक सर्वनाम',
    table: [
      { person: '1st Singular', subject: 'I', object: 'me', possAdj: 'my', possPron: 'mine', reflexive: 'myself' },
      { person: '2nd Singular', subject: 'you', object: 'you', possAdj: 'your', possPron: 'yours', reflexive: 'yourself' },
      { person: '3rd Singular Male', subject: 'he', object: 'him', possAdj: 'his', possPron: 'his', reflexive: 'himself' },
      { person: '3rd Singular Female', subject: 'she', object: 'her', possAdj: 'her', possPron: 'hers', reflexive: 'herself' },
      { person: '3rd Singular Neutral', subject: 'it', object: 'it', possAdj: 'its', possPron: 'its', reflexive: 'itself' },
      { person: '1st Plural', subject: 'we', object: 'us', possAdj: 'our', possPron: 'ours', reflexive: 'ourselves' },
      { person: '2nd Plural', subject: 'you', object: 'you', possAdj: 'your', possPron: 'yours', reflexive: 'yourselves' },
      { person: '3rd Plural', subject: 'they', object: 'them', possAdj: 'their', possPron: 'theirs', reflexive: 'themselves' },
    ],
    tip: 'Subject position (I/he/she/they) vs Object position (me/him/her/them) — mistake mat karo!',
    commonMistakes: [
      { wrong: 'Me and Ram went.', correct: 'Ram and I went.', why: 'Subject position में I, me नहीं' },
      { wrong: 'Between you and I.', correct: 'Between you and me.', why: 'Preposition के बाद object pronoun' },
    ],
  },
  DEMONSTRATIVE: {
    type: 'Demonstrative Pronouns',
    hindiLabel: 'संकेतवाचक सर्वनाम',
    items: [
      { word: 'this', use: 'Singular near', example: 'This is my phone.' },
      { word: 'that', use: 'Singular far', example: 'That is the Eiffel Tower.' },
      { word: 'these', use: 'Plural near', example: 'These are my friends.' },
      { word: 'those', use: 'Plural far', example: 'Those were good days.' },
    ],
  },
  RELATIVE: {
    type: 'Relative Pronouns',
    hindiLabel: 'संबंधवाचक सर्वनाम',
    items: [
      { word: 'who', use: 'For people (subject)', example: 'The man who called is outside.' },
      { word: 'whom', use: 'For people (object)', example: 'The man whom I met is here.' },
      { word: 'whose', use: 'For possession', example: 'The girl whose bag is red is my friend.' },
      { word: 'which', use: 'For things/animals', example: 'The book which I read was great.' },
      { word: 'that', use: 'For people or things', example: 'The car that I bought is red.' },
    ],
  },
  INTERROGATIVE: {
    type: 'Interrogative Pronouns',
    hindiLabel: 'प्रश्नवाचक सर्वनाम',
    items: [
      { word: 'who', use: 'Asking about person (subject)', example: 'Who is at the door?' },
      { word: 'whom', use: 'Asking about person (object)', example: 'Whom did you call?' },
      { word: 'whose', use: 'Asking about possession', example: 'Whose book is this?' },
      { word: 'which', use: 'Asking about choice', example: 'Which colour do you prefer?' },
      { word: 'what', use: 'Asking about thing/fact', example: 'What is your name?' },
    ],
  },
  INDEFINITE: {
    type: 'Indefinite Pronouns',
    hindiLabel: 'अनिश्चयवाचक सर्वनाम',
    items: [
      { word: 'someone/somebody', use: 'Positive — unknown person', example: 'Someone is at the door.' },
      { word: 'anyone/anybody', use: 'Questions & negatives — person', example: 'Is anyone there?' },
      { word: 'everyone/everybody', use: 'All people', example: 'Everyone is invited.' },
      { word: 'no one/nobody', use: 'Not any person', example: 'Nobody knows the answer.' },
      { word: 'something', use: 'Positive — unknown thing', example: 'Something smells good.' },
      { word: 'anything', use: 'Questions & negatives — thing', example: 'Do you need anything?' },
      { word: 'everything', use: 'All things', example: 'Everything is ready.' },
      { word: 'nothing', use: 'Not any thing', example: 'Nothing is impossible.' },
    ],
  },
};

// ── 6. PREPOSITIONS ───────────────────────────────────────────────────────────
export const PREPOSITIONS = {
  TIME: {
    category: 'Time Prepositions',
    hindiLabel: 'समय के लिए',
    items: [
      { prep: 'at', rule: 'Specific times, meal times, night', examples: ['at 5 PM', 'at noon', 'at night', 'at breakfast'] },
      { prep: 'in', rule: 'Months, years, seasons, parts of day, longer periods', examples: ['in January', 'in 2023', 'in summer', 'in the morning', 'in the evening'] },
      { prep: 'on', rule: 'Days and dates', examples: ['on Monday', 'on 15th August', 'on New Year\'s Day', 'on my birthday'] },
      { prep: 'since', rule: 'From a point in past to now', examples: ['since 2010', 'since Monday', 'since childhood'] },
      { prep: 'for', rule: 'Duration of time', examples: ['for 2 hours', 'for 3 years', 'for a long time'] },
      { prep: 'by', rule: 'Deadline — not later than', examples: ['by Friday', 'by 5 PM', 'by the end'] },
      { prep: 'until/till', rule: 'Up to a point in time', examples: ['until midnight', 'till Monday'] },
      { prep: 'during', rule: 'Throughout a period', examples: ['during the meeting', 'during summer'] },
      { prep: 'within', rule: 'Inside a time frame', examples: ['within 2 hours', 'within a week'] },
      { prep: 'after', rule: 'Later than a time', examples: ['after lunch', 'after 5 PM'] },
      { prep: 'before', rule: 'Earlier than a time', examples: ['before 9 AM', 'before the exam'] },
    ],
  },
  PLACE: {
    category: 'Place Prepositions',
    hindiLabel: 'स्थान के लिए',
    items: [
      { prep: 'at', rule: 'Specific point/location (general)', examples: ['at the bus stop', 'at school', 'at home', 'at the office'] },
      { prep: 'in', rule: 'Inside a closed space, city/country', examples: ['in the room', 'in Delhi', 'in India', 'in the box'] },
      { prep: 'on', rule: 'Surface, floor, street', examples: ['on the table', 'on the floor', 'on MG Road', 'on the wall'] },
      { prep: 'above', rule: 'Higher than, but not touching', examples: ['above the clouds', 'the shelf above the desk'] },
      { prep: 'below', rule: 'Lower than', examples: ['below sea level', 'below the table'] },
      { prep: 'under/beneath', rule: 'Directly below, covered by', examples: ['under the bridge', 'under the bed'] },
      { prep: 'over', rule: 'Directly above, covering', examples: ['over the door', 'a bridge over the river'] },
      { prep: 'between', rule: 'In the middle of two things', examples: ['between the two chairs', 'between Monday and Friday'] },
      { prep: 'among', rule: 'In the middle of three or more', examples: ['among the students', 'among friends'] },
      { prep: 'beside/next to', rule: 'Immediately to the side of', examples: ['sit beside me', 'next to the bank'] },
      { prep: 'opposite', rule: 'Directly facing', examples: ['opposite the station', 'sitting opposite her'] },
      { prep: 'near', rule: 'Not far from', examples: ['near the hospital', 'near my house'] },
    ],
  },
  MOVEMENT: {
    category: 'Movement Prepositions',
    hindiLabel: 'गति/दिशा के लिए',
    items: [
      { prep: 'to', rule: 'Direction toward a place', examples: ['go to school', 'walk to the door', 'fly to London'] },
      { prep: 'from', rule: 'Starting point', examples: ['come from Delhi', 'fly from Mumbai to Dubai'] },
      { prep: 'into', rule: 'Movement inside (entering)', examples: ['walk into the room', 'fall into the water'] },
      { prep: 'out of', rule: 'Movement from inside to outside', examples: ['walk out of the room', 'get out of the car'] },
      { prep: 'through', rule: 'Movement from one side to other', examples: ['drive through the tunnel', 'run through the park'] },
      { prep: 'across', rule: 'Movement from one side to other (surface/body)', examples: ['swim across the river', 'walk across the road'] },
      { prep: 'along', rule: 'Movement following a line', examples: ['walk along the road', 'swim along the shore'] },
      { prep: 'past', rule: 'Movement going beyond', examples: ['walk past the shop', 'drive past the school'] },
    ],
  },
};

// ── 7. CONJUNCTIONS ───────────────────────────────────────────────────────────
export const CONJUNCTIONS = {
  COORDINATING: {
    type: 'Coordinating Conjunctions',
    acronym: 'FANBOYS',
    hindiLabel: 'समानाधिकरण',
    items: [
      { word: 'for', use: 'Reason/cause', example: 'I stayed home, for it was raining.' },
      { word: 'and', use: 'Addition', example: 'She is smart and hardworking.' },
      { word: 'nor', use: 'Neither...nor — both negative', example: 'He neither ate nor slept.' },
      { word: 'but', use: 'Contrast', example: 'I tried but failed.' },
      { word: 'or', use: 'Alternative', example: 'Tea or coffee?' },
      { word: 'yet', use: 'Contrast (stronger than but)', example: 'She is poor yet happy.' },
      { word: 'so', use: 'Result/consequence', example: 'It rained, so we stayed home.' },
    ],
  },
  SUBORDINATING: {
    type: 'Subordinating Conjunctions',
    hindiLabel: 'व्यधिकरण',
    categories: [
      { label: 'Time', words: ['when', 'while', 'after', 'before', 'since', 'until', 'as soon as', 'once'], example: 'Call me when you arrive.' },
      { label: 'Reason/Cause', words: ['because', 'since', 'as', 'given that'], example: 'She left because she was tired.' },
      { label: 'Condition', words: ['if', 'unless', 'provided that', 'as long as'], example: 'I will go if you come.' },
      { label: 'Contrast', words: ['although', 'though', 'even though', 'whereas', 'while'], example: 'Although it rained, we went.' },
      { label: 'Purpose', words: ['so that', 'in order that', 'so as to'], example: 'Study so that you pass.' },
      { label: 'Result', words: ['so...that', 'such...that'], example: 'She was so tired that she slept immediately.' },
    ],
  },
  CORRELATIVE: {
    type: 'Correlative Conjunctions',
    hindiLabel: 'सहसंबंधी',
    items: [
      { pair: 'both...and', example: 'Both Ram and Shyam are here.', rule: 'Verb is plural' },
      { pair: 'either...or', example: 'Either she or he is wrong.', rule: 'Verb agrees with subject nearest to it' },
      { pair: 'neither...nor', example: 'Neither Ram nor Shyam came.', rule: 'Verb agrees with nearest subject' },
      { pair: 'not only...but also', example: 'She is not only smart but also kind.', rule: 'Emphasis on second item' },
      { pair: 'whether...or', example: 'I don\'t know whether to go or stay.', rule: 'Choice between two options' },
      { pair: 'as...as', example: 'She is as tall as her brother.', rule: 'Equal comparison' },
    ],
  },
};

// ── 8. QUESTION FORMATION ─────────────────────────────────────────────────────
export const QUESTION_FORMATION = {
  YES_NO_QUESTIONS: {
    type: 'Yes/No Questions',
    hindiLabel: 'हाँ/ना में जवाब देने वाले सवाल',
    rules: [
      'Auxiliary verb को subject से पहले लाओ',
      'Be verb: Are you ready? Was she there?',
      'Have verb: Have you eaten? Has she gone?',
      'Modal verbs: Can you swim? Will it rain?',
      'Do/Does/Did: Do you like it? Does she know? Did they come?',
    ],
    examples: [
      { statement: 'You are ready.', question: 'Are you ready?', rule: 'Be verb invert' },
      { statement: 'She has eaten.', question: 'Has she eaten?', rule: 'Have verb invert' },
      { statement: 'They can swim.', question: 'Can they swim?', rule: 'Modal invert' },
      { statement: 'He likes tea.', question: 'Does he like tea?', rule: 'Add does + V1' },
      { statement: 'They went home.', question: 'Did they go home?', rule: 'Add did + V1' },
    ],
  },
  WH_QUESTIONS: {
    type: 'WH-Questions',
    hindiLabel: 'WH सवाल',
    words: [
      { wh: 'What', use: 'Things, actions, information', example: 'What is your name? What are you doing?' },
      { wh: 'Who', use: 'Person (subject)', example: 'Who is calling? Who did this?' },
      { wh: 'Whom', use: 'Person (object)', example: 'Whom did you call? To whom did you speak?' },
      { wh: 'Which', use: 'Choice among options', example: 'Which book do you want? Which way?' },
      { wh: 'When', use: 'Time', example: 'When did you arrive? When is the meeting?' },
      { wh: 'Where', use: 'Place', example: 'Where are you? Where do you live?' },
      { wh: 'Why', use: 'Reason', example: 'Why are you late? Why did she leave?' },
      { wh: 'How', use: 'Manner, degree', example: 'How are you? How did you do this?' },
      { wh: 'How many', use: 'Countable quantity', example: 'How many brothers do you have?' },
      { wh: 'How much', use: 'Uncountable quantity/price', example: 'How much does it cost?' },
      { wh: 'How long', use: 'Duration', example: 'How long have you been waiting?' },
      { wh: 'How often', use: 'Frequency', example: 'How often do you exercise?' },
    ],
    structure: 'WH-word + Auxiliary + Subject + Main Verb + ?',
  },
  QUESTION_TAGS: {
    type: 'Question Tags',
    hindiLabel: 'पुष्टि के लिए जोड़े जाने वाले सवाल',
    rules: [
      'Positive statement → Negative tag: She is smart, isn\'t she?',
      'Negative statement → Positive tag: She isn\'t smart, is she?',
      'Tag में always pronoun use होता है (noun नहीं)',
      'Am → am I? / aren\'t I?',
      'Imperative → will you? (polite) / won\'t you?',
      'Let\'s → shall we?',
    ],
    examples: [
      { statement: 'You are coming,', tag: 'aren\'t you?' },
      { statement: 'She can swim,', tag: 'can\'t she?' },
      { statement: 'They didn\'t come,', tag: 'did they?' },
      { statement: 'I am right,', tag: 'aren\'t I?' },
      { statement: 'Let\'s go,', tag: 'shall we?' },
      { statement: 'Close the door,', tag: 'will you?' },
    ],
  },
};

// ── 9. PASSIVE VOICE ──────────────────────────────────────────────────────────
export const PASSIVE_VOICE = {
  rule: 'Object of active sentence → Subject of passive; Subject of active → by + agent (optional)',
  structure: 'Object + be (in correct tense) + Past Participle (V3) + by + Subject',
  conversions: [
    { tense: 'Simple Present',     active: 'She writes the letter.',         passive: 'The letter is written by her.' },
    { tense: 'Present Continuous', active: 'She is writing the letter.',     passive: 'The letter is being written by her.' },
    { tense: 'Present Perfect',    active: 'She has written the letter.',    passive: 'The letter has been written by her.' },
    { tense: 'Simple Past',        active: 'She wrote the letter.',          passive: 'The letter was written by her.' },
    { tense: 'Past Continuous',    active: 'She was writing the letter.',    passive: 'The letter was being written by her.' },
    { tense: 'Past Perfect',       active: 'She had written the letter.',    passive: 'The letter had been written by her.' },
    { tense: 'Simple Future',      active: 'She will write the letter.',     passive: 'The letter will be written by her.' },
    { tense: 'Future Perfect',     active: 'She will have written it.',      passive: 'It will have been written by her.' },
    { tense: 'Modal',              active: 'She can write the letter.',      passive: 'The letter can be written by her.' },
    { tense: 'Imperative',         active: 'Write the letter.',              passive: 'Let the letter be written.' },
  ],
  usedWhen: [
    'When the doer is unknown: My bike was stolen.',
    'When the doer is unimportant: The road was repaired.',
    'In formal/scientific writing: The experiment was conducted.',
    'When you want to emphasize the action or result over the doer.',
  ],
  commonMistakes: [
    { wrong: 'The letter was write by her.', correct: 'The letter was written by her.', why: 'Passive में V3 (written) चाहिए' },
    { wrong: 'By her the letter was written.', correct: 'The letter was written by her.', why: 'Object first, then by + agent' },
  ],
};

// ── 10. DIRECT & INDIRECT SPEECH ──────────────────────────────────────────────
export const REPORTED_SPEECH = {
  rules: [
    'Direct → Indirect में verb one tense back जाती है',
    'Present Simple → Past Simple',
    'Present Continuous → Past Continuous',
    'Present Perfect → Past Perfect',
    'Past Simple → Past Perfect',
    'Will → Would; Can → Could; May → Might; Shall → Should',
    'Pronouns बदलते हैं according to context',
    'Time/place words बदलते हैं: today → that day, here → there, now → then',
  ],
  tenseChanges: [
    { direct: 'is/am/are',       indirect: 'was/were' },
    { direct: 'is/am/are + ing', indirect: 'was/were + ing' },
    { direct: 'has/have + V3',   indirect: 'had + V3' },
    { direct: 'V2 (simple past)', indirect: 'had + V3 (past perfect)' },
    { direct: 'will',            indirect: 'would' },
    { direct: 'can',             indirect: 'could' },
    { direct: 'may',             indirect: 'might' },
    { direct: 'shall',           indirect: 'should' },
  ],
  timeChanges: [
    { direct: 'today',           indirect: 'that day' },
    { direct: 'yesterday',       indirect: 'the previous day / the day before' },
    { direct: 'tomorrow',        indirect: 'the next day / the following day' },
    { direct: 'now',             indirect: 'then' },
    { direct: 'here',            indirect: 'there' },
    { direct: 'this',            indirect: 'that' },
    { direct: 'these',           indirect: 'those' },
    { direct: 'last week',       indirect: 'the previous week' },
    { direct: 'next week',       indirect: 'the following week' },
  ],
  examples: [
    { type: 'Statement',  direct: 'She said, "I am hungry."',              indirect: 'She said that she was hungry.' },
    { type: 'Question',   direct: 'He asked, "Are you coming?"',           indirect: 'He asked if I was coming.' },
    { type: 'Command',    direct: 'Teacher said, "Open your books."',      indirect: 'Teacher told us to open our books.' },
    { type: 'Request',    direct: 'She said, "Please help me."',           indirect: 'She requested me to help her.' },
    { type: 'Exclamation',direct: 'He said, "What a beautiful view!"',    indirect: 'He exclaimed that it was a very beautiful view.' },
  ],
  reportingVerbs: {
    statements: ['said', 'told', 'mentioned', 'explained', 'claimed', 'stated', 'added', 'admitted'],
    questions: ['asked', 'enquired', 'wanted to know', 'wondered'],
    commands: ['ordered', 'told', 'commanded', 'instructed'],
    requests: ['requested', 'asked', 'begged', 'urged'],
    suggestions: ['suggested', 'advised', 'recommended', 'proposed'],
  },
};

// ── 11. CONDITIONALS ──────────────────────────────────────────────────────────
export const CONDITIONALS = {
  ZERO: {
    type: 'Zero Conditional',
    number: 0,
    hindiLabel: 'हमेशा सच — सामान्य सच्चाई',
    structure: 'If + Present Simple, Present Simple',
    use: 'Universal truths, scientific facts, things that are always true',
    example: 'If you heat water to 100°C, it boils.',
    hindiExample: 'अगर पानी 100°C तक गर्म करो, तो वह उबलता है।',
    moreExamples: [
      'If you don\'t water plants, they die.',
      'If it rains, the ground gets wet.',
      'If you mix red and blue, you get purple.',
    ],
    tip: 'If की जगह When भी use हो सकता है',
  },
  FIRST: {
    type: 'First Conditional',
    number: 1,
    hindiLabel: 'संभव भविष्य — Real / Possible',
    structure: 'If + Present Simple, will + V1',
    use: 'Real and possible situations in the future',
    example: 'If it rains tomorrow, I will stay home.',
    hindiExample: 'अगर कल बारिश होगी, तो मैं घर रहूँगा।',
    moreExamples: [
      'If you study hard, you will pass.',
      'If she calls, I will answer.',
      'If he doesn\'t hurry, he will miss the train.',
    ],
    tip: 'If clause में will नहीं — Present tense use करो',
    commonMistake: { wrong: 'If it will rain, I will stay.', correct: 'If it rains, I will stay.' },
  },
  SECOND: {
    type: 'Second Conditional',
    number: 2,
    hindiLabel: 'काल्पनिक वर्तमान — Unreal / Hypothetical',
    structure: 'If + Past Simple, would + V1',
    use: 'Imaginary or unlikely situations in the present/future',
    example: 'If I had a million dollars, I would travel the world.',
    hindiExample: 'अगर मेरे पास एक मिलियन डॉलर होते, तो मैं पूरी दुनिया घूमता।',
    moreExamples: [
      'If she were the president, she would change many things.',
      'If I lived near a beach, I would swim every day.',
      'What would you do if you lost your job?',
    ],
    tip: 'If clause में "were" (not was) use करो — If I were you',
    commonMistake: { wrong: 'If I would have money...', correct: 'If I had money...' },
  },
  THIRD: {
    type: 'Third Conditional',
    number: 3,
    hindiLabel: 'काल्पनिक भूतकाल — Unreal Past / Regret',
    structure: 'If + Past Perfect, would have + V3',
    use: 'Imagining how past events could have been different',
    example: 'If I had studied harder, I would have passed the exam.',
    hindiExample: 'अगर मैंने अधिक पढ़ा होता, तो परीक्षा पास कर लेता।',
    moreExamples: [
      'If she had taken medicine, she would have recovered faster.',
      'If he hadn\'t been late, he would have got the job.',
      'Would you have come if I had invited you?',
    ],
    tip: 'Past ki baat — already over — regret ya alternate history',
    commonMistake: { wrong: 'If I would have studied...', correct: 'If I had studied...' },
  },
  MIXED: {
    type: 'Mixed Conditional',
    hindiLabel: 'मिश्रित — Past Cause, Present Effect',
    structure: 'If + Past Perfect, would + V1',
    use: 'Past condition with a present result',
    example: 'If I had slept well, I would not be tired now.',
    hindiExample: 'अगर मैं अच्छे से सोया होता, तो अभी थका नहीं होता।',
    moreExamples: [
      'If she had taken that job, she would be in London now.',
      'If he had studied medicine, he would be a doctor today.',
    ],
    tip: 'Past perfect in if-clause + would + V1 in result clause',
  },
};

// ── 12. ACTIVE & PASSIVE VOICE STRUCTURES ────────────────────────────────────
export const VOICE_STRUCTURES = {
  ACTIVE:  { label: 'Active Voice',  structure: 'Subject + Verb + Object',               example: 'She wrote the letter.' },
  PASSIVE: { label: 'Passive Voice', structure: 'Object + be + Past Participle + by Sub', example: 'The letter was written by her.' },
};

// ── 13. IRREGULAR VERBS (100 most common) ────────────────────────────────────
export const IRREGULAR_VERBS = [
  { v1: 'be',       v2: 'was/were', v3: 'been',      hindi: 'होना' },
  { v1: 'beat',     v2: 'beat',     v3: 'beaten',     hindi: 'पीटना' },
  { v1: 'become',   v2: 'became',   v3: 'become',     hindi: 'बनना' },
  { v1: 'begin',    v2: 'began',    v3: 'begun',      hindi: 'शुरू करना' },
  { v1: 'bend',     v2: 'bent',     v3: 'bent',       hindi: 'झुकाना' },
  { v1: 'bite',     v2: 'bit',      v3: 'bitten',     hindi: 'काटना' },
  { v1: 'blow',     v2: 'blew',     v3: 'blown',      hindi: 'फूंकना' },
  { v1: 'break',    v2: 'broke',    v3: 'broken',     hindi: 'तोड़ना' },
  { v1: 'bring',    v2: 'brought',  v3: 'brought',    hindi: 'लाना' },
  { v1: 'build',    v2: 'built',    v3: 'built',      hindi: 'बनाना' },
  { v1: 'burn',     v2: 'burnt',    v3: 'burnt',      hindi: 'जलाना' },
  { v1: 'buy',      v2: 'bought',   v3: 'bought',     hindi: 'खरीदना' },
  { v1: 'catch',    v2: 'caught',   v3: 'caught',     hindi: 'पकड़ना' },
  { v1: 'choose',   v2: 'chose',    v3: 'chosen',     hindi: 'चुनना' },
  { v1: 'come',     v2: 'came',     v3: 'come',       hindi: 'आना' },
  { v1: 'cost',     v2: 'cost',     v3: 'cost',       hindi: 'लगना (दाम)' },
  { v1: 'cut',      v2: 'cut',      v3: 'cut',        hindi: 'काटना' },
  { v1: 'deal',     v2: 'dealt',    v3: 'dealt',      hindi: 'व्यवहार करना' },
  { v1: 'dig',      v2: 'dug',      v3: 'dug',        hindi: 'खोदना' },
  { v1: 'do',       v2: 'did',      v3: 'done',       hindi: 'करना' },
  { v1: 'draw',     v2: 'drew',     v3: 'drawn',      hindi: 'खींचना/बनाना' },
  { v1: 'drink',    v2: 'drank',    v3: 'drunk',      hindi: 'पीना' },
  { v1: 'drive',    v2: 'drove',    v3: 'driven',     hindi: 'चलाना' },
  { v1: 'eat',      v2: 'ate',      v3: 'eaten',      hindi: 'खाना' },
  { v1: 'fall',     v2: 'fell',     v3: 'fallen',     hindi: 'गिरना' },
  { v1: 'feel',     v2: 'felt',     v3: 'felt',       hindi: 'महसूस करना' },
  { v1: 'fight',    v2: 'fought',   v3: 'fought',     hindi: 'लड़ना' },
  { v1: 'find',     v2: 'found',    v3: 'found',      hindi: 'ढूंढना' },
  { v1: 'fly',      v2: 'flew',     v3: 'flown',      hindi: 'उड़ना' },
  { v1: 'forget',   v2: 'forgot',   v3: 'forgotten',  hindi: 'भूलना' },
  { v1: 'forgive',  v2: 'forgave',  v3: 'forgiven',   hindi: 'माफ करना' },
  { v1: 'freeze',   v2: 'froze',    v3: 'frozen',     hindi: 'जमाना' },
  { v1: 'get',      v2: 'got',      v3: 'gotten/got', hindi: 'पाना' },
  { v1: 'give',     v2: 'gave',     v3: 'given',      hindi: 'देना' },
  { v1: 'go',       v2: 'went',     v3: 'gone',       hindi: 'जाना' },
  { v1: 'grow',     v2: 'grew',     v3: 'grown',      hindi: 'बढ़ना' },
  { v1: 'hang',     v2: 'hung',     v3: 'hung',       hindi: 'लटकाना' },
  { v1: 'have',     v2: 'had',      v3: 'had',        hindi: 'होना/रखना' },
  { v1: 'hear',     v2: 'heard',    v3: 'heard',      hindi: 'सुनना' },
  { v1: 'hide',     v2: 'hid',      v3: 'hidden',     hindi: 'छुपाना' },
  { v1: 'hit',      v2: 'hit',      v3: 'hit',        hindi: 'मारना' },
  { v1: 'hold',     v2: 'held',     v3: 'held',       hindi: 'पकड़ना' },
  { v1: 'hurt',     v2: 'hurt',     v3: 'hurt',       hindi: 'चोट लगाना' },
  { v1: 'keep',     v2: 'kept',     v3: 'kept',       hindi: 'रखना' },
  { v1: 'know',     v2: 'knew',     v3: 'known',      hindi: 'जानना' },
  { v1: 'lead',     v2: 'led',      v3: 'led',        hindi: 'नेतृत्व करना' },
  { v1: 'learn',    v2: 'learnt',   v3: 'learnt',     hindi: 'सीखना' },
  { v1: 'leave',    v2: 'left',     v3: 'left',       hindi: 'छोड़ना' },
  { v1: 'lend',     v2: 'lent',     v3: 'lent',       hindi: 'उधार देना' },
  { v1: 'let',      v2: 'let',      v3: 'let',        hindi: 'अनुमति देना' },
  { v1: 'lie',      v2: 'lay',      v3: 'lain',       hindi: 'लेटना' },
  { v1: 'light',    v2: 'lit',      v3: 'lit',        hindi: 'जलाना' },
  { v1: 'lose',     v2: 'lost',     v3: 'lost',       hindi: 'खोना' },
  { v1: 'make',     v2: 'made',     v3: 'made',       hindi: 'बनाना' },
  { v1: 'mean',     v2: 'meant',    v3: 'meant',      hindi: 'मतलब होना' },
  { v1: 'meet',     v2: 'met',      v3: 'met',        hindi: 'मिलना' },
  { v1: 'pay',      v2: 'paid',     v3: 'paid',       hindi: 'भुगतान करना' },
  { v1: 'put',      v2: 'put',      v3: 'put',        hindi: 'रखना' },
  { v1: 'read',     v2: 'read',     v3: 'read',       hindi: 'पढ़ना' },
  { v1: 'ride',     v2: 'rode',     v3: 'ridden',     hindi: 'सवारी करना' },
  { v1: 'ring',     v2: 'rang',     v3: 'rung',       hindi: 'बजना' },
  { v1: 'rise',     v2: 'rose',     v3: 'risen',      hindi: 'उठना' },
  { v1: 'run',      v2: 'ran',      v3: 'run',        hindi: 'दौड़ना' },
  { v1: 'say',      v2: 'said',     v3: 'said',       hindi: 'कहना' },
  { v1: 'see',      v2: 'saw',      v3: 'seen',       hindi: 'देखना' },
  { v1: 'sell',     v2: 'sold',     v3: 'sold',       hindi: 'बेचना' },
  { v1: 'send',     v2: 'sent',     v3: 'sent',       hindi: 'भेजना' },
  { v1: 'shake',    v2: 'shook',    v3: 'shaken',     hindi: 'हिलाना' },
  { v1: 'shine',    v2: 'shone',    v3: 'shone',      hindi: 'चमकना' },
  { v1: 'show',     v2: 'showed',   v3: 'shown',      hindi: 'दिखाना' },
  { v1: 'shut',     v2: 'shut',     v3: 'shut',       hindi: 'बंद करना' },
  { v1: 'sing',     v2: 'sang',     v3: 'sung',       hindi: 'गाना' },
  { v1: 'sit',      v2: 'sat',      v3: 'sat',        hindi: 'बैठना' },
  { v1: 'sleep',    v2: 'slept',    v3: 'slept',      hindi: 'सोना' },
  { v1: 'speak',    v2: 'spoke',    v3: 'spoken',     hindi: 'बोलना' },
  { v1: 'spend',    v2: 'spent',    v3: 'spent',      hindi: 'खर्च करना' },
  { v1: 'stand',    v2: 'stood',    v3: 'stood',      hindi: 'खड़े रहना' },
  { v1: 'steal',    v2: 'stole',    v3: 'stolen',     hindi: 'चुराना' },
  { v1: 'swim',     v2: 'swam',     v3: 'swum',       hindi: 'तैरना' },
  { v1: 'take',     v2: 'took',     v3: 'taken',      hindi: 'लेना' },
  { v1: 'teach',    v2: 'taught',   v3: 'taught',     hindi: 'सिखाना' },
  { v1: 'tear',     v2: 'tore',     v3: 'torn',       hindi: 'फाड़ना' },
  { v1: 'tell',     v2: 'told',     v3: 'told',       hindi: 'बताना' },
  { v1: 'think',    v2: 'thought',  v3: 'thought',    hindi: 'सोचना' },
  { v1: 'throw',    v2: 'threw',    v3: 'thrown',     hindi: 'फेंकना' },
  { v1: 'understand',v2:'understood',v3:'understood',  hindi: 'समझना' },
  { v1: 'wake',     v2: 'woke',     v3: 'woken',      hindi: 'जागना' },
  { v1: 'wear',     v2: 'wore',     v3: 'worn',       hindi: 'पहनना' },
  { v1: 'win',      v2: 'won',      v3: 'won',        hindi: 'जीतना' },
  { v1: 'write',    v2: 'wrote',    v3: 'written',    hindi: 'लिखना' },
];

// ── 14. SENTENCE TYPES ────────────────────────────────────────────────────────
export const SENTENCE_TYPES = [
  { type: 'Declarative', use: 'Makes a statement', structure: 'S + V + O', example: 'She reads books.', hindi: 'कथनवाचक' },
  { type: 'Interrogative', use: 'Asks a question', structure: 'Aux + S + V?', example: 'Does she read books?', hindi: 'प्रश्नवाचक' },
  { type: 'Imperative', use: 'Gives a command or request', structure: 'V + O (no subject)', example: 'Read this book.', hindi: 'आज्ञावाचक' },
  { type: 'Exclamatory', use: 'Expresses strong emotion', structure: 'What/How + S + V!', example: 'What a beautiful book!', hindi: 'विस्मयवाचक' },
  { type: 'Simple', use: 'One independent clause', structure: 'S + V', example: 'She reads.', hindi: 'साधारण' },
  { type: 'Compound', use: 'Two independent clauses joined', structure: 'S+V + conjunction + S+V', example: 'She reads and he writes.', hindi: 'संयुक्त' },
  { type: 'Complex', use: 'One main + one subordinate clause', structure: 'Main clause + subordinate clause', example: 'She reads because she loves books.', hindi: 'मिश्रित' },
  { type: 'Compound-Complex', use: 'Two main + one subordinate clause', structure: 'Complex + Compound', example: 'She reads because she loves books, and he writes.', hindi: 'मिश्रित-संयुक्त' },
];

// ── 15. SUBJECT-VERB AGREEMENT RULES ─────────────────────────────────────────
export const SVA_RULES = [
  { rule: 'Singular subject → singular verb', example: 'She walks to school.' },
  { rule: 'Plural subject → plural verb', example: 'They walk to school.' },
  { rule: 'I → am/was (special case)', example: 'I am here. I was there.' },
  { rule: 'Compound subject with "and" → plural', example: 'Ram and Shyam are friends.' },
  { rule: 'Either/Neither + singular → singular verb', example: 'Either Ram or Shyam is wrong.' },
  { rule: 'Each/Every/Either/Neither → singular verb', example: 'Each student has a book.' },
  { rule: 'Collective nouns → usually singular', example: 'The team is playing well.' },
  { rule: 'Uncountable nouns → singular verb', example: 'Water is essential. News is good.' },
  { rule: '"A number of" → plural; "The number of" → singular', example: 'A number of students are present. The number of students is 30.' },
  { rule: 'Titles, books, subjects → singular', example: 'Mathematics is difficult. "The Hobbit" is a great book.' },
  { rule: 'None → can be singular or plural', example: 'None of them was/were present.' },
  { rule: 'With "along with/as well as/together with" → verb agrees with first subject', example: 'The teacher, along with students, is present.' },
];

// ── 16. DEGREES OF COMPARISON ─────────────────────────────────────────────────
export const DEGREES_OF_COMPARISON = {
  rules: [
    'One syllable: add -er (comparative) and -est (superlative)',
    'Two syllables ending in -y: change y to i, add -er/-est',
    'Two+ syllables: use more/most before the adjective',
    'Irregular adjectives have unique forms',
  ],
  regular: [
    { positive: 'tall',    comparative: 'taller',    superlative: 'tallest' },
    { positive: 'fast',    comparative: 'faster',    superlative: 'fastest' },
    { positive: 'happy',   comparative: 'happier',   superlative: 'happiest' },
    { positive: 'clever',  comparative: 'cleverer',  superlative: 'cleverest' },
    { positive: 'careful', comparative: 'more careful', superlative: 'most careful' },
    { positive: 'beautiful', comparative: 'more beautiful', superlative: 'most beautiful' },
    { positive: 'intelligent', comparative: 'more intelligent', superlative: 'most intelligent' },
  ],
  irregular: [
    { positive: 'good/well',  comparative: 'better',  superlative: 'best' },
    { positive: 'bad/ill',    comparative: 'worse',   superlative: 'worst' },
    { positive: 'much/many',  comparative: 'more',    superlative: 'most' },
    { positive: 'little',     comparative: 'less',    superlative: 'least' },
    { positive: 'far',        comparative: 'farther/further', superlative: 'farthest/furthest' },
    { positive: 'old',        comparative: 'older/elder', superlative: 'oldest/eldest' },
    { positive: 'late',       comparative: 'later/latter', superlative: 'latest/last' },
  ],
  structures: [
    { type: 'Comparative', structure: 'Adj-er + than', example: 'She is taller than me.' },
    { type: 'Superlative', structure: 'the + Adj-est', example: 'She is the tallest in the class.' },
    { type: 'Equal', structure: 'as + Adj + as', example: 'She is as tall as her sister.' },
    { type: 'Not equal', structure: 'not as + Adj + as', example: 'He is not as tall as his brother.' },
  ],
};

// ── DEFAULT EXPORT ────────────────────────────────────────────────────────────
export default {
  TENSES,
  PARTS_OF_SPEECH,
  MODAL_VERBS,
  ARTICLE_RULES,
  PRONOUNS,
  PREPOSITIONS,
  CONJUNCTIONS,
  QUESTION_FORMATION,
  PASSIVE_VOICE,
  REPORTED_SPEECH,
  CONDITIONALS,
  VOICE_STRUCTURES,
  IRREGULAR_VERBS,
  SENTENCE_TYPES,
  SVA_RULES,
  DEGREES_OF_COMPARISON,
};
