'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';
import { useParams } from 'next/navigation';
import { motion, AnimatePresence } from 'framer-motion';
import {
  ArrowLeft, ArrowRight, BookOpen, Target, Mic,
  CheckCircle2, ChevronDown, Star,
  PenTool, Brain, Zap,
  FileText, Trophy, XCircle,
  Headphones, BookOpenCheck, RotateCcw
} from 'lucide-react';
import { cn } from '@/lib/utils';

// ============================================================
// Sound Effect Hook (Web Audio API)
// ============================================================
function useSound() {
  const playSound = (type) => {
    try {
      const ctx = new (window.AudioContext || window.webkitAudioContext)();
      const osc = ctx.createOscillator();
      const gain = ctx.createGain();
      osc.connect(gain);
      gain.connect(ctx.destination);

      if (type === 'correct') {
        osc.type = 'sine';
        osc.frequency.setValueAtTime(523.25, ctx.currentTime); // C5
        osc.frequency.exponentialRampToValueAtTime(880, ctx.currentTime + 0.1); // A5
        gain.gain.setValueAtTime(0.1, ctx.currentTime);
        gain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.5);
        osc.start();
        osc.stop(ctx.currentTime + 0.5);
      } else if (type === 'wrong') {
        osc.type = 'sawtooth';
        osc.frequency.setValueAtTime(300, ctx.currentTime);
        osc.frequency.exponentialRampToValueAtTime(100, ctx.currentTime + 0.3);
        gain.gain.setValueAtTime(0.1, ctx.currentTime);
        gain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.3);
        osc.start();
        osc.stop(ctx.currentTime + 0.3);
      } else if (type === 'reveal') {
        osc.type = 'triangle';
        osc.frequency.setValueAtTime(440, ctx.currentTime);
        gain.gain.setValueAtTime(0.05, ctx.currentTime);
        gain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.2);
        osc.start();
        osc.stop(ctx.currentTime + 0.2);
      }
    } catch (e) {
      console.log('Audio not supported or interaction needed first');
    }
  };
  return playSound;
}

// ============================================================
// Data Mocks (Expanding to simulate massive content)
// ============================================================
// ============================================================
// Data Fetching Hook
// ============================================================
function useDayData(dayNum) {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function loadData() {
      try {
        setLoading(true);
        // Dynamically import the massive JSON payload generated by scripts/generate_all_days.js
        // We use a relative path trick or fetch if this was served as static asset.
        // In Next.js, importing from outside the project tree can be tricky if it's dynamic.
        // Assuming we fetch from an API route or it's accessible.
        // For local development, we will fetch it assuming we expose a simple API or just statically import it if possible.
        // The safest robust way in Next.js for client components to read massive local JSON files is an API route.
        const res = await fetch(`/api/challenge/${dayNum}`);
        if (res.ok) {
          const json = await res.json();
          setData(json);
        } else {
          console.error("Failed to load day data, using fallback.");
        }
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    }
    loadData();
  }, [dayNum]);

  return { data, loading };
}

const LESSON_SECTIONS = [
  { id: 'concept',      icon: BookOpen,     label: 'Concept & Theory',          color: 'text-indigo-400', bg: 'bg-indigo-500/10' },
  { id: 'vocabulary',   icon: FileText,     label: 'Vocabulary',                 color: 'text-cyan-400', bg: 'bg-cyan-500/10' },
  { id: 'practice',     icon: Target,       label: 'Interactive Practice',       color: 'text-emerald-400', bg: 'bg-emerald-500/10' },
  { id: 'speaking',     icon: Mic,          label: 'Speaking & Pronunciation',   color: 'text-pink-400', bg: 'bg-pink-500/10' },
  { id: 'writing',      icon: PenTool,      label: 'Writing Drills',             color: 'text-rose-400', bg: 'bg-rose-500/10' },
  { id: 'listening',    icon: Headphones,   label: 'Listening Practice',         color: 'text-sky-400', bg: 'bg-sky-500/10' },
  { id: 'reading',      icon: BookOpenCheck,label: 'Reading Comprehension',      color: 'text-lime-400', bg: 'bg-lime-500/10' },
  { id: 'revision',     icon: RotateCcw,    label: 'Revision & Quick Quiz',      color: 'text-orange-400', bg: 'bg-orange-500/10' },
  { id: 'test',         icon: Brain,        label: 'Final Mock Test',            color: 'text-violet-400', bg: 'bg-violet-500/10' },
];

// ============================================================
// Main Page Component
// ============================================================
export default function DayPage() {
  const params = useParams();
  const dayNum = parseInt(params?.day || '1', 10);
  
  const { data, loading } = useDayData(dayNum);
  
  const topic = data?.topic || {
    title: 'Loading Topic...', emoji: '⏳', cefr: 'A1', difficulty: 'beginner', type: 'grammar'
  };
  const content = data?.content || {
    explanation: 'Loading massive data payload...', rules: [], memoryTrick: ''
  };

  const [activeSection, setActiveSection] = useState('concept');
  const [sectionsDone, setSectionsDone] = useState({});
  const playSound = useSound();

  const markSectionDone = (id) => {
    if (!sectionsDone[id]) {
      setSectionsDone((prev) => ({ ...prev, [id]: true }));
      // addXP(10); // if userStore exists
      playSound('correct');
    }
  };

  const prevDay = dayNum > 1 ? dayNum - 1 : null;
  const nextDay = dayNum < 75 ? dayNum + 1 : null;

  const progressPct = (Object.keys(sectionsDone).length / LESSON_SECTIONS.length) * 100;

  if (loading && !data) {
    return (
      <div className="max-w-4xl mx-auto py-16">
        <div className="rounded-2xl border border-slate-800 bg-slate-900/80 p-8 text-center">
          <p className="text-xl font-semibold text-white">Loading Day {dayNum}...</p>
          <p className="text-slate-400 mt-2">Fetching lesson data and practice content.</p>
        </div>
      </div>
    );
  }

  return (
    <motion.div 
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5, ease: 'easeOut' }}
      className="max-w-5xl mx-auto space-y-8 pb-32"
    >
      {/* ── Breadcrumb ─────────────────────────────────────── */}
      <nav className="flex items-center gap-2 text-sm text-slate-500 font-medium">
        <Link href="/75-days-challenge" className="hover:text-white transition-colors flex items-center gap-1">
          <ArrowLeft size={16} /> 75 Days Challenge
        </Link>
        <span>/</span>
        <span className="text-primary-400">Day {dayNum}</span>
      </nav>

      {/* ── Topic Header (Animated & Modern) ──────────────────────────────────── */}
      <motion.div 
        layoutId="topic-header"
        className="relative overflow-hidden rounded-3xl bg-slate-900 border border-slate-800 p-8 shadow-2xl"
      >
        <div className="absolute top-0 right-0 w-64 h-64 bg-primary-500/10 rounded-full blur-3xl -translate-y-1/2 translate-x-1/3" />
        
        <div className="relative z-10 flex flex-col md:flex-row md:items-center gap-6">
          <div className="w-24 h-24 rounded-2xl bg-gradient-to-br from-primary-500/20 to-secondary-500/20 border border-primary-500/30 flex items-center justify-center text-5xl shrink-0 shadow-inner">
            {topic.emoji}
          </div>

          <div className="flex-1 space-y-2">
            <div className="flex flex-wrap items-center gap-2">
              <span className="px-3 py-1 text-xs font-bold uppercase tracking-wider rounded-full bg-primary-500 text-white shadow-lg shadow-primary-500/30">Day {dayNum}</span>
              <span className="px-3 py-1 text-xs font-bold rounded-full bg-slate-800 text-slate-300 border border-slate-700">{topic.cefr}</span>
              <span className={cn("px-3 py-1 text-xs font-bold uppercase tracking-wider rounded-full border", 
                topic.difficulty === 'beginner' ? 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20' :
                'bg-amber-500/10 text-amber-400 border-amber-500/20'
              )}>{topic.difficulty}</span>
            </div>
            <h1 className="text-4xl md:text-5xl font-black text-white tracking-tight">{topic.title}</h1>
            <p className="text-slate-400 text-lg capitalize">{topic.type} Masterclass</p>
          </div>
        </div>

        {/* Overall progress for this day */}
        <div className="mt-8 pt-6 border-t border-slate-800">
          <div className="flex justify-between text-sm font-semibold text-slate-400 mb-3">
            <span>Today's Progress</span>
            <span className="text-white">{Object.keys(sectionsDone).length} of {LESSON_SECTIONS.length} Completed</span>
          </div>
          <div className="h-3 rounded-full bg-slate-800 overflow-hidden shadow-inner">
            <motion.div
              initial={{ width: 0 }}
              animate={{ width: `${progressPct}%` }}
              transition={{ duration: 1, ease: 'easeInOut' }}
              className="h-full rounded-full bg-gradient-to-r from-primary-500 via-accent-500 to-secondary-500 relative"
            >
              <div className="absolute inset-0 bg-white/20 w-full h-full animate-pulse" />
            </motion.div>
          </div>
        </div>
      </motion.div>

      {/* ── Lesson Sections List ──────────────────────────── */}
      <div className="space-y-4">
        {LESSON_SECTIONS.map(({ id, icon: Icon, label, color, bg }, index) => {
          const isDone = sectionsDone[id];
          const isActive = activeSection === id;

          return (
            <motion.div 
              key={id} 
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: index * 0.1 }}
              className={cn(
                "rounded-2xl overflow-hidden border transition-all duration-300",
                isActive ? "bg-slate-900 border-primary-500/50 shadow-lg shadow-primary-500/10" : "bg-slate-900/50 border-slate-800 hover:border-slate-700"
              )}
            >
              {/* Section Header */}
              <button
                onClick={() => {
                  setActiveSection(isActive ? null : id);
                  if (!isDone && isActive) markSectionDone(id);
                }}
                className="w-full flex items-center gap-5 p-6 text-left group"
              >
                <div className={cn("w-14 h-14 rounded-2xl flex items-center justify-center shrink-0 transition-transform group-hover:scale-110", isDone ? 'bg-emerald-500/20' : bg)}>
                  {isDone ? <CheckCircle2 size={24} className="text-emerald-400" /> : <Icon size={24} className={color} />}
                </div>
                <div className="flex-1">
                  <h3 className="font-bold text-white text-xl">{label}</h3>
                  <p className="text-sm text-slate-400 mt-1">
                    {isDone ? <span className="text-emerald-400 font-medium">Completed ✨</span> : 'Click to expand and learn'}
                  </p>
                </div>
                <div className="flex items-center gap-4">
                  {!isDone && (
                    <span className="hidden sm:inline-block px-3 py-1 rounded-lg bg-primary-500/10 text-primary-400 text-sm font-bold border border-primary-500/20">+100 XP</span>
                  )}
                  <motion.div animate={{ rotate: isActive ? 180 : 0 }} transition={{ duration: 0.3 }}>
                    <ChevronDown size={24} className="text-slate-500" />
                  </motion.div>
                </div>
              </button>

              {/* Section Content */}
              <AnimatePresence>
                {isActive && (
                  <motion.div 
                    initial={{ height: 0, opacity: 0 }}
                    animate={{ height: 'auto', opacity: 1 }}
                    exit={{ height: 0, opacity: 0 }}
                    className="overflow-hidden"
                  >
                    <div className="px-6 pb-8 border-t border-slate-800 pt-6">
                      {id === 'concept' && <ConceptSection topic={topic} content={content} onComplete={() => markSectionDone(id)} />}
                      {id === 'vocabulary' && <VocabularyMassive vocabulary={data?.vocabulary || []} onComplete={() => markSectionDone(id)} />}
                      {id === 'practice' && <InteractivePractice practiceQs={data?.practice || []} playSound={playSound} onComplete={() => markSectionDone(id)} />}
                      {id === 'speaking' && <SpeakingAdvanced topic={topic} practiceQs={data?.practice || []} onComplete={() => markSectionDone(id)} />}
                      {id === 'writing' && <WritingAdvanced topic={topic} content={content} vocabulary={data?.vocabulary || []} practiceQs={data?.practice || []} onComplete={() => markSectionDone(id)} />}
                      {id === 'listening' && <ListeningPractice listening={data?.listening} onComplete={() => markSectionDone(id)} />}
                      {id === 'reading' && <ReadingComprehension reading={data?.reading} onComplete={() => markSectionDone(id)} />}
                      {id === 'revision' && <RevisionQuiz revision={data?.revision} onComplete={() => markSectionDone(id)} />}
                      {id === 'test' && <MockTestEngine dayNum={dayNum} mockTest={data?.mockTest || []} onComplete={() => markSectionDone(id)} />}
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </motion.div>
          );
        })}
      </div>

      {/* ── Navigation ─────────────────────────────────────── */}
      <div className="flex justify-between items-center pt-8">
        {prevDay ? (
          <Link href={`/75-days-challenge/${prevDay}`} className="px-6 py-3 rounded-xl bg-slate-800 text-white font-semibold flex items-center gap-2 hover:bg-slate-700 transition-colors">
            <ArrowLeft size={18} /> Previous Day
          </Link>
        ) : <div />}

        {nextDay ? (
          <Link href={`/75-days-challenge/${nextDay}`} className="px-8 py-4 rounded-xl bg-primary-600 text-white font-bold flex items-center gap-3 hover:bg-primary-500 transition-all hover:scale-105 shadow-lg shadow-primary-500/25">
            Proceed to Day {nextDay} <ArrowRight size={20} />
          </Link>
        ) : (
          <div className="px-8 py-4 rounded-xl bg-gradient-to-r from-amber-500 to-orange-500 text-white font-bold text-lg shadow-lg shadow-amber-500/25">
            🎉 Challenge Completed!
          </div>
        )}
      </div>
    </motion.div>
  );
}

// ============================================================
// Specialized Detailed Sections
// ============================================================

function ConceptSection({ topic, content, onComplete }) {
  const renderBold = (text) => {
    const parts = text.split(/\*\*(.*?)\*\*/g);
    return parts.map((part, i) => i % 2 === 1 ? <strong key={i} className="text-white font-bold">{part}</strong> : <span key={i}>{part}</span>);
  };

  return (
    <div className="space-y-8">
      <div className="prose prose-invert max-w-none">
        <h2 className="text-2xl font-bold text-white border-b border-slate-800 pb-4 flex items-center gap-3">
          <BookOpen className="text-indigo-400" /> Deep Dive: {topic.title}
        </h2>
        <div className="bg-indigo-500/5 p-6 rounded-2xl border border-indigo-500/20 mt-6 space-y-4 text-lg text-slate-300 leading-relaxed">
          {content?.explanation?.split('\n').map((line, i) => (
            <p key={i}>{renderBold(line)}</p>
          ))}
        </div>
      </div>
      
      <div className="grid md:grid-cols-2 gap-6">
        <div className="bg-slate-800/50 p-6 rounded-2xl border border-slate-700">
          <h3 className="text-xl font-bold text-white mb-4 flex items-center gap-2"><Star className="text-amber-400" /> Key Rules</h3>
          <ul className="space-y-3">
            {content?.rules?.map((rule, i) => (
              <li key={i} className="flex items-start gap-3 text-slate-300">
                <CheckCircle2 size={20} className="text-emerald-400 shrink-0 mt-1" />
                <span>{rule}</span>
              </li>
            ))}
          </ul>
        </div>
        <div className="bg-gradient-to-br from-amber-500/10 to-orange-500/10 p-6 rounded-2xl border border-amber-500/20">
          <h3 className="text-xl font-bold text-amber-400 mb-4 flex items-center gap-2"><Zap /> Memory Trick</h3>
          <p className="text-lg text-amber-100/90 font-medium">{content?.memoryTrick}</p>
        </div>
      </div>

      <button onClick={onComplete} className="w-full py-4 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white font-bold text-lg transition-colors shadow-lg shadow-indigo-500/25">
        I understand this concept
      </button>
    </div>
  );
}

// Massive Vocabulary Viewer with Pagination
function VocabularyMassive({ vocabulary, onComplete }) {
  const allWords = vocabulary.length > 0 ? vocabulary : [{ word: 'Loading...', hindi: '...', example: '...' }];
  const [page, setPage] = useState(1);
  const wordsPerPage = 20;
  const totalPages = Math.ceil(allWords.length / wordsPerPage);
  
  const currentWords = allWords.slice(0, page * wordsPerPage);

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-end">
        <div>
          <h3 className="text-2xl font-bold text-white">Daily Vocabulary</h3>
          <p className="text-slate-400">Master these words to sound native. (Showing {currentWords.length} of {allWords.length})</p>
        </div>
        <div className="text-sm font-bold text-cyan-400 bg-cyan-500/10 px-4 py-2 rounded-full border border-cyan-500/20">
          {allWords.length} Words Total
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <AnimatePresence>
          {currentWords.map((item, i) => (
            <motion.div 
              key={i}
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              className="p-5 rounded-2xl bg-slate-800 border border-slate-700 hover:border-cyan-500/50 transition-all group"
            >
              <div className="flex justify-between items-start mb-3">
                <div>
                  <h4 className="text-xl font-bold text-white group-hover:text-cyan-400 transition-colors">{item.word}</h4>
                  <span className="text-sm text-slate-500 font-mono">{item.ipa}</span>
                </div>
                <span className="text-lg font-medium text-amber-400 hindi-text bg-amber-400/10 px-3 py-1 rounded-lg border border-amber-400/20">{item.hindi}</span>
              </div>
              <p className="text-sm text-slate-300 italic bg-slate-900/50 p-3 rounded-xl border border-slate-800">
                "{item.example}"
              </p>
            </motion.div>
          ))}
        </AnimatePresence>
      </div>

      {page < totalPages && (
        <button 
          onClick={() => setPage(p => p + 1)}
          className="w-full py-4 rounded-xl border-2 border-dashed border-slate-600 text-slate-300 font-bold hover:border-cyan-500 hover:text-cyan-400 transition-all"
        >
          Load More Words...
        </button>
      )}

      {page === totalPages && (
        <button onClick={onComplete} className="w-full py-4 rounded-xl bg-cyan-600 hover:bg-cyan-500 text-white font-bold text-lg transition-colors shadow-lg shadow-cyan-500/25">
          Mark Vocabulary as Reviewed
        </button>
      )}
    </div>
  );
}

function normalizeAnswerText(text) {
  return (text || '')
    .toLowerCase()
    .replace(/[^a-z0-9 ]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function isAnswerCorrect(userInput, question) {
  const candidate = normalizeAnswerText(userInput);
  if (!candidate) return false;

  const accepted = [
    question?.english,
    ...(Array.isArray(question?.alternatives) ? question.alternatives : []),
  ].filter(Boolean);

  return accepted.some((answer) => normalizeAnswerText(answer) === candidate);
}

// Highly Interactive Practice Engine (Hindi -> English)
function InteractivePractice({ practiceQs, playSound, onComplete }) {
  const allQs = practiceQs.length > 0 ? practiceQs : [{ id: 1, hindi: 'Loading...', english: 'Loading...' }];
  const [currentIndex, setCurrentIndex] = useState(0);
  const [userInput, setUserInput] = useState('');
  const [status, setStatus] = useState('idle'); // idle, correct, wrong, revealed
  const [score, setScore] = useState(0);

  const currentQ = allQs[currentIndex];

  const checkAnswer = () => {
    if (!userInput.trim()) return;

    if (isAnswerCorrect(userInput, currentQ)) {
      setStatus('correct');
      playSound('correct');
      setScore(s => s + 10);
    } else {
      setStatus('wrong');
      playSound('wrong');
    }
  };

  const revealAnswer = () => {
    setStatus('revealed');
    playSound('reveal');
  };

  const nextQuestion = () => {
    if (currentIndex < allQs.length - 1) {
      setCurrentIndex(i => i + 1);
      setUserInput('');
      setStatus('idle');
    } else {
      onComplete();
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center mb-6">
        <div>
          <h3 className="text-2xl font-bold text-white">Interactive Translation</h3>
          <p className="text-slate-400">Translate Hindi to English. Capitalization & punctuation ignored.</p>
        </div>
        <div className="flex items-center gap-4">
          <div className="text-xl font-black text-amber-400 flex items-center gap-2"><Trophy size={24} /> {score} XP</div>
          <div className="px-4 py-2 bg-slate-800 rounded-lg text-slate-300 font-bold border border-slate-700">
            {currentIndex + 1} / {allQs.length}
          </div>
        </div>
      </div>

      <div className="bg-slate-900 border border-slate-700 rounded-3xl p-8 relative overflow-hidden shadow-2xl">
        <div className="absolute top-0 left-0 w-full h-1 bg-slate-800">
          <motion.div 
            className="h-full bg-emerald-500" 
            initial={{ width: 0 }} 
            animate={{ width: `${((currentIndex) / allQs.length) * 100}%` }} 
          />
        </div>

        <div className="mb-8 text-center">
          <span className="inline-block px-3 py-1 bg-slate-800 text-slate-400 text-xs font-bold rounded-full mb-4 uppercase tracking-widest border border-slate-700">Translate this</span>
          <h2 className="text-3xl md:text-4xl font-black text-white hindi-text leading-tight">"{currentQ.hindi}"</h2>
        </div>

        <div className="space-y-4">
          <textarea
            value={userInput}
            onChange={(e) => { setUserInput(e.target.value); setStatus('idle'); }}
            placeholder="Type your English translation here..."
            className="w-full p-6 rounded-2xl bg-slate-800 border-2 border-slate-700 text-white text-xl focus:border-primary-500 focus:ring-4 focus:ring-primary-500/20 transition-all resize-none outline-none placeholder:text-slate-600"
            rows={3}
            disabled={status === 'correct' || status === 'revealed'}
          />

          <AnimatePresence mode="wait">
            {status === 'correct' && (
              <motion.div initial={{ opacity:0, y:-10 }} animate={{opacity:1, y:0}} exit={{opacity:0}} className="p-4 rounded-xl bg-emerald-500/20 border border-emerald-500/50 flex items-center gap-3 text-emerald-400">
                <CheckCircle2 size={24} /> <span className="text-lg font-bold">Perfect Translation! +10 XP</span>
              </motion.div>
            )}
            {status === 'wrong' && (
              <motion.div initial={{ opacity:0, y:-10 }} animate={{opacity:1, y:0}} exit={{opacity:0}} className="p-4 rounded-xl bg-rose-500/20 border border-rose-500/50 flex flex-col gap-2 text-rose-400">
                <div className="flex items-center gap-3"><XCircle size={24} /> <span className="text-lg font-bold">Not quite right. Try again or reveal answer.</span></div>
              </motion.div>
            )}
            {status === 'revealed' && (
              <motion.div initial={{ opacity:0, y:-10 }} animate={{opacity:1, y:0}} exit={{opacity:0}} className="p-6 rounded-xl bg-amber-500/10 border border-amber-500/30 text-center">
                <p className="text-slate-400 text-sm mb-2 uppercase tracking-widest font-bold">Correct Answer</p>
                <p className="text-2xl font-black text-amber-400">{currentQ.english}</p>
              </motion.div>
            )}
          </AnimatePresence>

          <div className="flex gap-4 pt-4">
            {(status === 'idle' || status === 'wrong') && (
              <>
                <button onClick={checkAnswer} className="flex-1 py-4 rounded-xl bg-primary-600 hover:bg-primary-500 text-white font-bold text-lg transition-all active:scale-95 shadow-lg shadow-primary-600/30">
                  Check Answer
                </button>
                <button onClick={revealAnswer} className="px-6 py-4 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 font-bold transition-all border border-slate-700">
                  Reveal
                </button>
              </>
            )}
            {(status === 'correct' || status === 'revealed') && (
              <button onClick={nextQuestion} className="w-full py-4 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white font-bold text-lg transition-all active:scale-95 shadow-lg shadow-emerald-600/30 flex items-center justify-center gap-2">
                Next Question <ArrowRight size={20} />
              </button>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

function SpeakingAdvanced({ topic, practiceQs, onComplete }) {
  const speakingItems = (practiceQs || []).slice(0, 8);
  const [currentIndex, setCurrentIndex] = useState(0);
  const [showReference, setShowReference] = useState(false);

  if (!speakingItems.length) {
    return <p className="text-slate-400">Speaking drills are loading...</p>;
  }

  const current = speakingItems[currentIndex];
  const completionPercent = Math.round(((currentIndex + 1) / speakingItems.length) * 100);

  return (
    <div className="space-y-5">
      <div className="rounded-2xl border border-pink-500/30 bg-pink-500/5 p-5">
        <h3 className="text-2xl font-black text-white mb-2">Speaking Lab — {topic.title}</h3>
        <p className="text-slate-300">Read the Hindi prompt, speak the English translation aloud, then compare with the reference answer.</p>
      </div>

      <div className="rounded-2xl border border-slate-700 bg-slate-900 p-6 space-y-4">
        <div className="flex items-center justify-between text-sm text-slate-400">
          <span>Prompt {currentIndex + 1} / {speakingItems.length}</span>
          <span>{completionPercent}% session progress</span>
        </div>
        <div className="h-2 bg-slate-800 rounded-full overflow-hidden">
          <div className="h-full bg-pink-500" style={{ width: `${completionPercent}%` }} />
        </div>
        <p className="text-xl md:text-2xl text-white hindi-text font-semibold">{current.hindi}</p>

        <div className="flex flex-wrap gap-3">
          <button
            onClick={() => setShowReference(v => !v)}
            className="px-4 py-2 rounded-lg border border-pink-500/40 bg-pink-500/10 text-pink-300 font-semibold"
          >
            {showReference ? 'Hide Reference' : 'Reveal Reference'}
          </button>
          <button
            onClick={() => setCurrentIndex((idx) => Math.max(0, idx - 1))}
            disabled={currentIndex === 0}
            className="px-4 py-2 rounded-lg border border-slate-700 text-slate-300 disabled:opacity-40"
          >
            Previous
          </button>
          <button
            onClick={() => setCurrentIndex((idx) => Math.min(speakingItems.length - 1, idx + 1))}
            disabled={currentIndex === speakingItems.length - 1}
            className="px-4 py-2 rounded-lg border border-slate-700 text-slate-300 disabled:opacity-40"
          >
            Next
          </button>
        </div>

        {showReference && (
          <div className="rounded-xl bg-emerald-500/10 border border-emerald-500/30 p-4">
            <p className="text-xs uppercase tracking-wide text-emerald-300 mb-1">Reference translation</p>
            <p className="text-lg font-bold text-white">{current.english}</p>
          </div>
        )}
      </div>

      <button
        onClick={onComplete}
        className="w-full py-3 rounded-xl bg-pink-600 hover:bg-pink-500 text-white font-bold"
      >
        Mark Speaking Session Complete
      </button>
    </div>
  );
}

function WritingAdvanced({ topic, content, vocabulary, practiceQs, onComplete }) {
  const [draft, setDraft] = useState('');
  const prompt = `Write 6-10 sentences about "${topic.title}" using at least 3 words from today's vocabulary.`;
  const vocabSuggestions = (vocabulary || []).slice(0, 6).map((item) => item.word);
  const referenceSentences = (practiceQs || []).slice(0, 3).map((item) => item.english);
  const wordCount = draft.trim() ? draft.trim().split(/\s+/).length : 0;

  return (
    <div className="space-y-5">
      <div className="rounded-2xl border border-rose-500/30 bg-rose-500/5 p-5">
        <h3 className="text-2xl font-black text-white mb-2">Writing Drill — {topic.title}</h3>
        <p className="text-slate-300">{prompt}</p>
      </div>

      <div className="grid gap-4 md:grid-cols-2">
        <div className="rounded-xl border border-slate-700 bg-slate-900 p-4">
          <p className="text-sm font-semibold text-rose-300 mb-2">Use these vocabulary words</p>
          <div className="flex flex-wrap gap-2">
            {vocabSuggestions.map((word) => (
              <span key={word} className="px-2 py-1 rounded-md bg-slate-800 text-slate-200 text-sm border border-slate-700">{word}</span>
            ))}
          </div>
        </div>
        <div className="rounded-xl border border-slate-700 bg-slate-900 p-4">
          <p className="text-sm font-semibold text-indigo-300 mb-2">Sentence references</p>
          <ul className="space-y-2 text-sm text-slate-300 list-disc list-inside">
            {referenceSentences.map((sentence, idx) => <li key={`${sentence}-${idx}`}>{sentence}</li>)}
          </ul>
        </div>
      </div>

      <textarea
        value={draft}
        onChange={(e) => setDraft(e.target.value)}
        placeholder="Write your paragraph here..."
        rows={8}
        className="w-full rounded-2xl bg-slate-900 border border-slate-700 p-4 text-white focus:border-rose-500/60 outline-none"
      />
      <div className="flex justify-between text-sm text-slate-400">
        <span>Words: {wordCount}</span>
        <span>{wordCount >= 40 ? 'Good length ✅' : 'Target: at least 40 words'}</span>
      </div>

      {content?.rules?.length > 0 && (
        <div className="rounded-xl border border-amber-500/30 bg-amber-500/5 p-4">
          <p className="text-sm font-semibold text-amber-300 mb-2">Before submitting, check:</p>
          <ul className="text-sm text-slate-300 space-y-1 list-disc list-inside">
            {content.rules.slice(0, 3).map((rule, idx) => <li key={`${rule}-${idx}`}>{rule}</li>)}
          </ul>
        </div>
      )}

      <button
        onClick={onComplete}
        className="w-full py-3 rounded-xl bg-rose-600 hover:bg-rose-500 text-white font-bold"
      >
        Mark Writing Drill Complete
      </button>
    </div>
  );
}

function MockTestEngine({ dayNum, mockTest, onComplete }) {
  const questions = (mockTest || []).slice(0, 20);
  const [started, setStarted] = useState(false);
  const [index, setIndex] = useState(0);
  const [input, setInput] = useState('');
  const [score, setScore] = useState(0);
  const [revealed, setRevealed] = useState(false);
  const [submitted, setSubmitted] = useState(false);

  if (!questions.length) {
    return <p className="text-slate-400">Mock test is loading...</p>;
  }

  const current = questions[index];

  const submitAnswer = () => {
    if (!input.trim() || submitted) return;
    if (isAnswerCorrect(input, current)) {
      setScore((s) => s + 1);
    }
    setSubmitted(true);
  };

  const next = () => {
    if (index < questions.length - 1) {
      setIndex((i) => i + 1);
      setInput('');
      setRevealed(false);
      setSubmitted(false);
      return;
    }
    onComplete();
  };

  const progress = Math.round((index / questions.length) * 100);
  const finalPercentage = Math.round((score / questions.length) * 100);

  if (!started) {
    return (
      <div className="space-y-5 text-center">
        <h3 className="text-3xl font-black text-white">Day {dayNum} Real Data Mock Test</h3>
        <p className="text-slate-300">20 translation questions selected from today&apos;s real dataset.</p>
        <button onClick={() => setStarted(true)} className="px-8 py-3 rounded-xl bg-violet-600 hover:bg-violet-500 text-white font-bold">
          Start Mock Test
        </button>
      </div>
    );
  }

  const completed = submitted && index === questions.length - 1;

  return (
    <div className="space-y-5">
      <div className="flex justify-between text-sm text-slate-400">
        <span>Question {index + 1} / {questions.length}</span>
        <span>Score: {score}</span>
      </div>
      <div className="h-2 bg-slate-800 rounded-full overflow-hidden">
        <div className="h-full bg-violet-500" style={{ width: `${progress}%` }} />
      </div>

      <div className="rounded-2xl border border-slate-700 bg-slate-900 p-5 space-y-3">
        <p className="text-lg text-white hindi-text font-semibold">{current.hindi}</p>
        <textarea
          value={input}
          onChange={(e) => setInput(e.target.value)}
          rows={3}
          disabled={submitted}
          placeholder="Type your translation..."
          className="w-full rounded-xl bg-slate-800 border border-slate-700 p-3 text-white outline-none"
        />

        <div className="flex flex-wrap gap-3">
          <button onClick={submitAnswer} disabled={submitted} className="px-4 py-2 rounded-lg bg-violet-600 text-white font-semibold disabled:opacity-40">
            Submit
          </button>
          <button onClick={() => setRevealed((v) => !v)} className="px-4 py-2 rounded-lg border border-slate-700 text-slate-300">
            {revealed ? 'Hide Answer' : 'Reveal Answer'}
          </button>
          <button onClick={next} disabled={!submitted && !revealed} className="px-4 py-2 rounded-lg bg-emerald-600 text-white font-semibold disabled:opacity-40">
            {index === questions.length - 1 ? 'Finish' : 'Next'}
          </button>
        </div>

        {(revealed || submitted) && (
          <div className="rounded-xl border border-emerald-500/30 bg-emerald-500/10 p-3">
            <p className="text-xs uppercase tracking-wide text-emerald-300 mb-1">Correct answer</p>
            <p className="text-white font-semibold">{current.english}</p>
          </div>
        )}
      </div>

      {completed && (
        <div className="rounded-xl border border-amber-500/30 bg-amber-500/10 p-4 text-center">
          <p className="text-amber-300 font-semibold">Final Score: {score}/{questions.length} ({finalPercentage}%)</p>
          <p className="text-slate-300 text-sm mt-1">{finalPercentage >= 80 ? 'Excellent performance 🎉' : 'Keep practicing and retry for 80%+.'}</p>
        </div>
      )}
    </div>
  );
}

// ============================================================
// Listening Practice — fill-in-the-blank + dictation, from
// listening-exercise.json (served via /api/challenge/[day])
// ============================================================
function ListeningPractice({ listening, onComplete }) {
  const exercises = listening?.exercises || [];
  const dictationPassages = listening?.dictationPassages || (listening?.dictationPassage ? [listening.dictationPassage] : []);
  const [index, setIndex] = useState(0);
  const [answers, setAnswers] = useState({});
  const [checked, setChecked] = useState({});
  const [showDictation, setShowDictation] = useState(false);
  const playSound = useSound();

  if (!exercises.length) {
    return (
      <div className="space-y-4 text-center">
        <p className="text-slate-400">No listening exercises are available for this day yet.</p>
        <button onClick={onComplete} className="px-6 py-3 rounded-xl bg-sky-600 hover:bg-sky-500 text-white font-bold">
          Mark as Reviewed
        </button>
      </div>
    );
  }

  const current = exercises[index];
  const blankCount = (current.fillInBlank.match(/_____/g) || []).length;

  const speak = (text) => {
    if (typeof window === 'undefined' || !window.speechSynthesis) return;
    window.speechSynthesis.cancel();
    const utterance = new SpeechSynthesisUtterance(text);
    utterance.lang = 'en-US';
    utterance.rate = 0.85;
    window.speechSynthesis.speak(utterance);
  };

  const setBlankValue = (blankIdx, value) => {
    setAnswers((prev) => ({ ...prev, [`${index}-${blankIdx}`]: value }));
  };

  const checkAnswers = () => {
    const isCorrect = current.answer.every((expected, i) =>
      normalizeAnswerText(answers[`${index}-${i}`] || '') === normalizeAnswerText(expected)
    );
    setChecked((prev) => ({ ...prev, [index]: isCorrect }));
    playSound(isCorrect ? 'correct' : 'wrong');
  };

  const next = () => {
    if (index < exercises.length - 1) {
      setIndex((i) => i + 1);
    } else {
      setShowDictation(true);
      onComplete();
    }
  };

  const blankParts = current.fillInBlank.split('_____');

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center text-sm text-slate-400">
        <span>Listening Exercise {index + 1} / {exercises.length}</span>
        <span className="text-sky-400 font-semibold">{Object.values(checked).filter(Boolean).length} correct so far</span>
      </div>

      <div className="rounded-2xl border border-sky-500/30 bg-sky-500/5 p-6 space-y-4">
        <div className="flex items-center gap-3">
          <button
            onClick={() => speak(current.audioText)}
            className="w-12 h-12 rounded-full bg-sky-600 hover:bg-sky-500 text-white flex items-center justify-center shrink-0"
            title="Listen"
          >
            <Headphones size={20} />
          </button>
          <p className="text-slate-400 text-sm">Click to hear the sentence, then fill in the blanks below.</p>
        </div>

        <p className="text-lg text-white leading-relaxed flex flex-wrap items-center gap-2">
          {blankParts.map((part, i) => (
            <span key={i} className="flex items-center gap-2">
              {part}
              {i < blankCount && (
                <input
                  value={answers[`${index}-${i}`] || ''}
                  onChange={(e) => setBlankValue(i, e.target.value)}
                  className="w-28 px-2 py-1 rounded-lg bg-slate-800 border border-slate-600 text-white text-center outline-none focus:border-sky-500"
                />
              )}
            </span>
          ))}
        </p>

        <p className="text-sm text-amber-200/80 hindi-text">{current.hindi}</p>

        <div className="flex flex-wrap gap-3">
          <button onClick={checkAnswers} className="px-4 py-2 rounded-lg bg-sky-600 hover:bg-sky-500 text-white font-semibold">
            Check Answers
          </button>
          <button onClick={next} className="px-4 py-2 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white font-semibold">
            {index === exercises.length - 1 ? 'Finish & See Dictation' : 'Next Exercise'}
          </button>
        </div>

        {checked[index] !== undefined && (
          <div className={cn("rounded-xl p-3 border", checked[index] ? "border-emerald-500/30 bg-emerald-500/10 text-emerald-300" : "border-red-500/30 bg-red-500/10 text-red-300")}>
            {checked[index] ? 'Correct! Great listening.' : `Not quite. Correct answer: ${current.answer.join(', ')}`}
          </div>
        )}
      </div>

      {showDictation && dictationPassages.length > 0 && (
        <div className="rounded-2xl border border-slate-700 bg-slate-900 p-6 space-y-4">
          <h4 className="text-xl font-bold text-white flex items-center gap-2"><Headphones className="text-sky-400" size={20} /> Dictation Practice</h4>
          {dictationPassages.map((passage, i) => (
            <div key={i} className="space-y-2 border-t border-slate-800 pt-4 first:border-t-0 first:pt-0">
              <button onClick={() => speak(passage.text)} className="text-sm text-sky-400 font-semibold hover:text-sky-300">▶ Listen to full passage {i + 1}</button>
              <p className="text-slate-300 text-sm leading-relaxed">{passage.text}</p>
              <p className="text-amber-200/70 text-sm hindi-text">{passage.hindi}</p>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

// ============================================================
// Reading Comprehension — passages + MCQ, from
// reading-exercise.json (served via /api/challenge/[day])
// ============================================================
function ReadingComprehension({ reading, onComplete }) {
  const passages = reading?.passages || (reading?.passage ? [{ ...reading.passage, comprehensionQuestions: reading.comprehensionQuestions }] : []);
  const [passageIndex, setPassageIndex] = useState(0);
  const [showTranslation, setShowTranslation] = useState(false);
  const [selected, setSelected] = useState({});

  if (!passages.length) {
    return (
      <div className="space-y-4 text-center">
        <p className="text-slate-400">No reading passages are available for this day yet.</p>
        <button onClick={onComplete} className="px-6 py-3 rounded-xl bg-lime-600 hover:bg-lime-500 text-white font-bold">
          Mark as Reviewed
        </button>
      </div>
    );
  }

  const passage = passages[passageIndex];
  const questions = passage.comprehensionQuestions || [];
  const answeredAll = questions.length === 0 || questions.every((q) => selected[q.id] !== undefined);
  const correctCount = questions.filter((q) => selected[q.id] === q.answer).length;

  const selectOption = (qId, option) => {
    setSelected((prev) => ({ ...prev, [qId]: option }));
  };

  const nextPassage = () => {
    if (passageIndex < passages.length - 1) {
      setPassageIndex((i) => i + 1);
      setSelected({});
      setShowTranslation(false);
    } else {
      onComplete();
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center text-sm text-slate-400">
        <span>Passage {passageIndex + 1} / {passages.length}</span>
        <button onClick={() => setShowTranslation((v) => !v)} className="text-lime-400 font-semibold hover:text-lime-300">
          {showTranslation ? 'Hide Hindi Translation' : 'Show Hindi Translation'}
        </button>
      </div>

      <div className="rounded-2xl border border-lime-500/30 bg-lime-500/5 p-6 space-y-4">
        <h4 className="text-xl font-bold text-white">{passage.title}</h4>
        <p className="text-slate-300 leading-relaxed">{passage.text}</p>
        {showTranslation && (
          <p className="text-amber-200/80 text-sm leading-relaxed hindi-text border-t border-slate-800 pt-3">{passage.hindiTranslation}</p>
        )}
      </div>

      <div className="space-y-4">
        <h5 className="font-bold text-white">Comprehension Questions</h5>
        {questions.map((q) => (
          <div key={q.id} className="rounded-xl border border-slate-700 bg-slate-900 p-4 space-y-3">
            <p className="text-white font-semibold">{q.question}</p>
            <p className="text-xs text-amber-200/60 hindi-text">{q.hindi}</p>
            <div className="grid sm:grid-cols-2 gap-2">
              {q.options.map((opt) => {
                const isChosen = selected[q.id] === opt;
                const isRevealed = selected[q.id] !== undefined;
                const isRight = opt === q.answer;
                return (
                  <button
                    key={opt}
                    onClick={() => selectOption(q.id, opt)}
                    disabled={isRevealed}
                    className={cn(
                      "px-3 py-2 rounded-lg border text-sm text-left transition-colors",
                      isRevealed && isRight && "border-emerald-500 bg-emerald-500/10 text-emerald-300",
                      isRevealed && isChosen && !isRight && "border-red-500 bg-red-500/10 text-red-300",
                      !isRevealed && "border-slate-700 text-slate-300 hover:border-lime-500/50"
                    )}
                  >
                    {opt}
                  </button>
                );
              })}
            </div>
          </div>
        ))}
      </div>

      {answeredAll && (
        <div className="rounded-xl border border-amber-500/30 bg-amber-500/10 p-4 flex items-center justify-between">
          <p className="text-amber-300 font-semibold">Score: {correctCount}/{questions.length}</p>
          <button onClick={nextPassage} className="px-4 py-2 rounded-lg bg-lime-600 hover:bg-lime-500 text-white font-semibold">
            {passageIndex === passages.length - 1 ? 'Finish Reading' : 'Next Passage'}
          </button>
        </div>
      )}
    </div>
  );
}

// ============================================================
// Revision & Quick Quiz — from revision.json (served via
// /api/challenge/[day])
// ============================================================
function RevisionQuiz({ revision, onComplete }) {
  const keyPoints = revision?.keyPointsSummary || [];
  const rules = revision?.mustRememberRules || [];
  const quiz = revision?.quickQuiz || [];
  const [quizIndex, setQuizIndex] = useState(0);
  const [input, setInput] = useState('');
  const [revealed, setRevealed] = useState(false);
  const [score, setScore] = useState(0);

  if (!revision) {
    return <p className="text-slate-400">Revision content is loading...</p>;
  }

  const currentQ = quiz[quizIndex];
  const done = quiz.length === 0 || quizIndex >= quiz.length;

  const checkQuiz = () => {
    if (normalizeAnswerText(input) === normalizeAnswerText(currentQ.answer)) {
      setScore((s) => s + 1);
    }
    setRevealed(true);
  };

  const nextQuiz = () => {
    if (quizIndex < quiz.length - 1) {
      setQuizIndex((i) => i + 1);
      setInput('');
      setRevealed(false);
    } else {
      setQuizIndex(quiz.length);
      onComplete();
    }
  };

  return (
    <div className="space-y-8">
      <div className="grid md:grid-cols-2 gap-6">
        <div className="rounded-2xl border border-orange-500/30 bg-orange-500/5 p-6">
          <h4 className="text-lg font-bold text-white mb-3 flex items-center gap-2"><Star className="text-orange-400" size={18} /> Key Points Summary</h4>
          <ul className="space-y-2 text-sm text-slate-300 list-disc list-inside">
            {keyPoints.map((kp, i) => <li key={i}>{kp}</li>)}
          </ul>
        </div>
        <div className="rounded-2xl border border-slate-700 bg-slate-900 p-6">
          <h4 className="text-lg font-bold text-white mb-3 flex items-center gap-2"><Zap className="text-amber-400" size={18} /> Must-Remember Rules</h4>
          <ul className="space-y-2 text-sm text-slate-300 list-disc list-inside">
            {rules.map((r, i) => <li key={i}>{r}</li>)}
          </ul>
        </div>
      </div>

      {!done && currentQ && (
        <div className="rounded-2xl border border-orange-500/30 bg-orange-500/5 p-6 space-y-3">
          <div className="flex justify-between text-sm text-slate-400">
            <span>Quick Quiz {quizIndex + 1} / {quiz.length}</span>
            <span>Score: {score}</span>
          </div>
          <p className="text-white font-semibold">{currentQ.question}</p>
          <input
            value={input}
            onChange={(e) => setInput(e.target.value)}
            disabled={revealed}
            placeholder="Type your answer..."
            className="w-full px-3 py-2 rounded-lg bg-slate-800 border border-slate-700 text-white outline-none focus:border-orange-500"
          />
          <div className="flex gap-3">
            {!revealed ? (
              <button onClick={checkQuiz} className="px-4 py-2 rounded-lg bg-orange-600 hover:bg-orange-500 text-white font-semibold">Check</button>
            ) : (
              <button onClick={nextQuiz} className="px-4 py-2 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white font-semibold">
                {quizIndex === quiz.length - 1 ? 'Finish Revision' : 'Next Question'}
              </button>
            )}
          </div>
          {revealed && (
            <p className="text-sm text-emerald-300">Correct answer: {currentQ.answer}</p>
          )}
        </div>
      )}

      {done && (
        <div className="rounded-xl border border-emerald-500/30 bg-emerald-500/10 p-4 text-center space-y-3">
          <p className="text-emerald-300 font-semibold">
            {quiz.length > 0 ? `Revision complete! Final quiz score: ${score}/${quiz.length}` : 'No quick quiz available yet — review the points above.'}
          </p>
          {quiz.length === 0 && (
            <button onClick={onComplete} className="px-6 py-3 rounded-xl bg-orange-600 hover:bg-orange-500 text-white font-bold">
              Mark Revision as Reviewed
            </button>
          )}
        </div>
      )}
    </div>
  );
}
